neuralmagic/deepsparse

Makefile, setup.py
this PR introduces a Makefile argument and modifies `setup.py` so nightly packages can be built with
```
make build BUILD_ARGS=nightly
```
`dist` directory contents after building:
```
deepsparse_nightly-0.1.0.20210208-py3-none-any.whl  deepsparse-nightly-0.1.0.20210208.tar.gz
```
=> Makefile build argument for nightly builds

setup.cfg, setup.py, src/deepsparse/engine.py
* enable one line SparseZoo integrations
* added an optional progress bar for benchmarking (tqdm should be a nested dependency)
```
benchmark_model(
"zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenette/base-none",
sample_input,
show_progress=True,
)
```
=> add compile engine from SparseZoo stub and benchmarking progress bar

setup.py, src/deepsparse/engine.py
This adds support for batch-splitting in the engine, i.e. if the number of the sockets on the system is > 1, then the model is split into batch_size/num_sockets smaller models which each run on their own socket.
Batch splitting will be enabled whenever num_sockets >1.
=> Batch splitting

README.md, docs/source/index.rst
Temporarily removing references to 7x and blog. Will return after it's live.
=> Rm: blog link, 7x

src/deepsparse/version.py
I didn't look at the last pull request closely enough.  The default splash message should only be generated if generated-version.py is not present.  Otherwise it will be provided by generated-version.py.
=> Only generate default splash message if generated-version.py does not exist

setup.py
Remove onnx and onnxruntime max version restrictions so they can install with python 3.9.
=> Support python3.9

Makefile, docs/source/scheduler.md, examples/classification/benchmark.py, examples/flask/server.py, examples/huggingface-transformers/benchmark.py, examples/huggingface-transformers/pipelines.py, examples/huggingface-transformers/squad_eval.py, examples/huggingface-transformers/squad_inference.py, examples/ultralytics-yolo/annotate.py, examples/ultralytics-yolo/benchmark.py, src/deepsparse/engine.py
Summary: Callers specify a core count and depend on the engine to figure out how to distribute them across sockets.
=> Deprecate sockets in the API, as suggested by Mark.

docs/source/c++api-overview.md
I've added a num_threads field to the engine's config structure.  It can be used to select the number of worker threads in the engine.
=> Add documentation for num_threads in engine config struct

src/deepsparse/cpu.py
When arch.bin fails it will create a dummy json object with a more detailed error message.
=> Better failure message when arch.bin fails

setup.cfg, src/deepsparse/transformers/__init__.py, src/deepsparse/transformers/helpers.py, src/deepsparse/transformers/pipelines.py
for convienence when packaging/moving around sparse transformer model exports, this PR adds support for passing a single model directory that will load the onnx file, model config, and tokenizer config into the pipeline.
a model directory should contain files such as `['model.onnx', 'config.json', 'tokenizer.json']`. Future work for model ONNX exporting will help with packaging.
priority for a config/tokenizer will be value directly passed into kwarg of pipelie -> config file from model dir -> default config from huggingface.co identifier
This PR also does a small refactor of `deepsparse.transformers` to add a helpers file and moves the `transformers` install check to the package level
=> load transformers onnx pipeline from model directory

docs/source/scheduler.md, src/deepsparse/engine.py
The elastic scheduler distributes requests across NUMA nodes rather than opportunistically multi-streaming them within a single node. This eliminates cache contention between requests which is beneficial for many workloads.
=> Add support for the elastic scheduler.

src/deepsparse/transformers/__init__.py, src/deepsparse/transformers/helpers.py, src/deepsparse/transformers/pipelines.py, src/deepsparse/transformers/server/main.py, src/deepsparse/transformers/server/utils.py
Bugfix: float32 object not JSON Serializable for `deepsparse.transformers.run_inference`
* Move `fix_numpy_types` functions from server.utils to deepsparse.transformers.helpers module
* Update usages accordingly
=> Bugfix: numpy float32 object not JSON Serializable

src/deepsparse/transformers/__init__.py, src/deepsparse/transformers/helpers.py, src/deepsparse/transformers/pipelines.py, src/deepsparse/transformers/server/main.py, src/deepsparse/transformers/server/utils.py
* Bugfix: float32 object not JSON Serializable for `deepsparse.transformers.run_inference`
* Move `fix_numpy_types` functions from server.utils to deepsparse.transformers.helpers module
* Update usages accordingly
* Bugfix: Address review Comments
* Removed `numpy` alias
* Added a comment before wrapping `pipeline_object` in `process_dataset`
=> [cherry-pick] numpy float32 object not JSON Serializable (#240)

src/deepsparse/transformers/pipelines.py, src/deepsparse/transformers/server/main.py, src/deepsparse/transformers/server/schemas.py, src/deepsparse/transformers/server/throttled_engine.py, src/deepsparse/transformers/server/utils.py
* Default `TASK` to `None`
* Return None or Empty Request/response Models
* Removed extraneous modification of globals
* Added config file support 
* Write each output on a new line for deepsparse.transformers.run_inference
=> Bugfixes: usage display + config support

examples/huggingface-transformers/requirements.txt, src/deepsparse/transformers/server/main.py
Removed: Unsupported install pathway, `deepsparse[transformers]`, now dependencies are installed automatically if `NM_NO_AUTOINSTALL_TRANSFORMERS` env variable is not set
=> Removed: Unsupported install pathway, `deepsparse[transformers]`

setup.py, src/deepsparse/transformers/eval_downstream.py
Allows evaluating trained BERT models on downstream datasets: squad, mnli, qqp, sst2
```
deepsparse.transformers.eval_downstream zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned_quant_3layers-aggressive_89 --dataset squad
100%|█████████████████████████████████████████████████████████████████████| 10570/10570 [03:49<00:00, 46.02it/s]
SQuAD eval results: {'exact_match': 69.10122989593188, 'f1': 78.35950221732533}
```
=> Add `deepsparse.transformers.eval_downstream` for BERT

setup.py, src/deepsparse/benchmark_model/benchmark_model.py, src/deepsparse/benchmark_model/ort_engine.py, src/deepsparse/benchmark_model/stream_benchmark.py, src/deepsparse/cpu.py, src/deepsparse/engine.py, src/deepsparse/transformers/server/utils.py
Adds a new `--engine` argument that can select between `deepsparse` and `onnxruntime`
Running with `--engine deepsparse` (the default)
```
deepsparse.benchmark zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned_quant_3layers-aggressive_84 -s async -t 1 -e deepsparse 
[INFO benchmark_model.py:217 ] Thread pinning to cores enabled
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.10.0 (434a2b34) (optimized) (system=avx512, binary=avx512)
[INFO benchmark_model.py:270 ] deepsparse.engine.Engine:
onnx_file_path: /home/mgoin/.cache/sparsezoo/0857c6f2-13c1-43c9-8db8-8f89a548dccd/model.onnx
batch_size: 1
num_cores: 18
scheduler: Scheduler.multi_stream
cpu_avx_type: avx512
cpu_vnni: False
[INFO            onnx.py:176 ] Generating input 'input_ids', type = …
```
=> Add onnxruntime backend to `deepsparse.benchmark`

Makefile
Add an optional variable to the Makefile to allow passing custom flags to the pytest commands.
=> Accept configurable pytest args from env var

src/deepsparse/benchmark_model/benchmark_model.py, src/deepsparse/benchmark_model/stream_benchmark.py
Also fix a bug where default num_streams could be 0 for 1 core
=> Add warmup_time to deepsparse.benchmark

setup.py, src/deepsparse/analyze.py, src/deepsparse/benchmark_model/benchmark_model.py
Adds a simple to run script that provides a simplified table to view the results of `analyze_model()`, so it is quick to view the performance profile of a model.
```
deepsparse.analyze zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned_quant-aggressive_95 -i "[1,128]" -q
Analyzing model: zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned_quant-aggressive_95
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.12.0 (514d3953) (optimized) (system=avx512, binary=avx512)
== Layer Breakdown ==
Name                           | Summed Time | Percent Taken
Naive Subgraph 0               |    0.181    | 3.80%
elementwise                    |    0.232    | 4.88%
reduce                         |    0.573    | 12.04%
shuffle …
```
=> Add `deepsparse.analyze`

README.md, src/deepsparse/benchmark_model/README.md, src/deepsparse/server/README.md
fixed yaml indentation for `server` readme.
=> Fix deepsparse readme

examples/benchmark/check_correctness.py
Hack up check_correctness.py so that we can override input shapes
=> Allow input overrides in check_correctness.py

examples/sparseserver-ui/README.md, examples/sparseserver-ui/client/settings.py, examples/sparseserver-ui/server/big-config.yaml
changed number of models to 19 instead of 20. Edited accordingly to match this new state.
=> SparseServer edit

src/deepsparse/transformers/eval_downstream.py
Fixes QQP, SST2, and MNLI dataset pipelines
=> Update label mapping for deepsparse.transformers.eval_downstream

src/deepsparse/benchmark/benchmark_model.py, src/deepsparse/benchmark/benchmark_sweep.py, src/deepsparse/engine.py
Gives a functional code interface into the benchmarks that `deepsparse.benchmark` runs
=> Expose `benchmark_model` and `benchmark_sweep` functions

src/deepsparse/engine.py
The current Implementation of `MultiModelEngine` has a bug where it refers to context properties as functions, this PR fixes that by removing paranthesis [python calls respective property functions automatically under the hood]
TLDR; if props are referred to with paranthesis an exception of the following form is thrown: `An object of ..... type is not callable`. This PR fixes that
=> [BugFix] Remove paranthesis when asking for context properties

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/nli_text_classification.py, src/deepsparse/transformers/pipelines/zero_shot_text_classification.py
This PR's main contributions are supporting static labels such that a user can pass a list of labels at model creation time. Because the number of labels is always known, the batch_size is set to num_labels * num_sequences. As such, batch_size was removed from documentation and replaced with num_sequences which specifies the number of sequences per inference.
This PR also adds hypothesis_template as an optional input which overrides the hypothesis_template in the config.
```
pipeline = Pipeline.create(task="zero_shot_text_classification", num_sequences=2, labels="politics,sports,art")
pipeline(sequences=["political statement", "artistic statement"])
```
=> Zero shot static labels

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/pipeline.py, src/deepsparse/transformers/pipelines/question_answering.py, src/deepsparse/transformers/pipelines/text_classification.py, src/deepsparse/transformers/pipelines/token_classification.py
This PR adds `Bucketing` support to transformer based Tasks.
Bucketing refers to the transformation of a set of items into categories or bins. 
In our context, we wanted to run multiple buckets (or instances of Pipeline objects) in the background (initialized with different sequence lengths) and dynamically route each input example to the Pipeline object most suited for that example (for now based on sequence length, but can be extended to other criterions like batch_size, ..., etc)
This PR adds a `Bucketable` contract/interface that describes methods needed to make a Pipeline support Bucketing functionality, On top of that we also add a `BucketingPipeline` proxy object that emulates a `Pipeline` but uses `Bucketing` under the hood. We create an instances of `BucketingPipeline` on the fly …
=> Add a BucketingPipeline

MANIFEST.in
The functions needed for the artifact store functionality to work in setup.py aren't included by default in the source distribution
https://packaging.python.org/en/latest/guides/using-manifest-in/
=> Add `utils/artifacts.py` to MANIFEST

MANIFEST.in
The functions needed for the artifact store functionality to work in setup.py aren't included by default in the source distribution
https://packaging.python.org/en/latest/guides/using-manifest-in/
=> [cherrypick] Add `utils/artifacts.py` to MANIFEST (#495)

src/deepsparse/pipeline.py, src/deepsparse/transformers/eval_downstream.py, src/deepsparse/transformers/pipelines/mnli_text_classification.py, src/deepsparse/transformers/pipelines/zero_shot_text_classification.py
This PR does 3 things
* changes the output when the pipeline is fed a string. Before, feeding a str would result in sequences=["my sequence"], now it's sequences="my sequence". This change supports...
* tests for eval_downstream. Since zero shot text classification shares the sst2 dataset with text classification, I added an argument to eval_downstream that modifies the task with "_zero_shot"
* Minor fixes to documentation
=> zeroshot eval_downstream, slight input change, doc updates

.github/workflows/test-check.yaml, Makefile, tests/test_server.py
The server CLI tests currently have a presumably inadvertently left-in use of `pdb` and also fail due to some unfortunate logger names in recent uvicorn. This name, `uvicorn.error`, triggers an assert that looks at the server’s output. This assert has been disabled but left in (to ideally re-enable it at a later time); let me know if it should just be deleted instead.
Also, this includes a small change to the Makefile to fix the `nobase` TARGET to properly ignore the base tests with their new organization under `tests/deepsparse`.
=> Fix server CLI tests

docker/Dockerfile, src/deepsparse/yolact/pipelines.py, src/deepsparse/yolact/schemas.py, src/deepsparse/yolo/pipelines.py, tests/deepsparse/pipelines/data_helpers.py, tests/deepsparse/pipelines/test_dynamic_batch_pipeline.py
This PR adds dynamic batch support to Yolact Pipelines, before this PR a YOLACT pipeline could only operate on a fixed static batch size, with this PR it can now accept inputs with different batch sizes.
Tests:
Automated test for YOLACT pipeline added. The tests were green locally.
Note: Right now the base branch is `bugfix-yolact-static-pipeline` to make the review process easier. Also because this PR relies on changes from #542. The base branch should be changed to `yolact-fixes` before landing
=> Add: Dynamic batch support for YOLACT Pipelines

src/deepsparse/yolact/pipelines.py, src/deepsparse/yolact/schemas.py, src/deepsparse/yolo/pipelines.py, tests/deepsparse/pipelines/data_helpers.py, tests/deepsparse/pipelines/test_dynamic_batch_pipeline.py
This PR is a combination of two different PRs namely #543 + BugFix
Description for BugFix:
This PR fixes a bug in Yolact static Pipeline where inputs for batch_size > 1 were not being processed correctly.
**also includes dynamic batch support, see comment and #843 for details**
The bug was in `process_inputs` function, where (for example sake) a batch of two images was being returned as `[ndarray(1, 3, 550, 550), ndarray(1, 3, 550, 550)]` instead of `[ndarray(2, 3, 550, 550)]`. This PR fixes that.
Tests:
```python
inputs = {
"images": ["./test_images/buddy.jpeg", "./test_images/basilica.jpg"]
}
pipe = Pipeline.create(
task="yolact",
batch_size=2,
)
print(pipe.use_dynamic_batch())
print(pipe(**inputs))
``` 
Before this PR the above test would fail with the …
=> Bugfix + Dynamic batch Support for Yolact

setup.py, src/deepsparse/image_classification/__init__.py, src/deepsparse/yolact/__init__.py
Bump max `torchvision` version from `0.10.1` to `0.12.0`, to support `python3.10`
implicitly increases the `torch` version to `1.11.0`
Test
```bash
git checkout bump-torchvision-version && \
pip install -e "./[yolo]" 
```
=> Bump max `torchvision` version 

setup.py, src/deepsparse/image_classification/__init__.py, src/deepsparse/yolact/__init__.py
Bump max `torchvision` version from `0.10.1` to `0.12.0`, implicitly increases the `torch` version to `1.11.0`
This has been done to add pre-liminary `python3.10` support
=> [cherry-pick] Bump max `torchvision` version 

src/deepsparse/transformers/pipelines/mnli_text_classification.py
These were issues that were brought up in QA. Both of these argument checks cause errors during run time, but can be checked at pipeline instantiation time.
=> zscp: argument checks for hypothesis template and nli indexes

src/deepsparse/image_classification/schemas.py
Remove: `numpy.ndarray` from ImageClassification schema to work with `deepsparse.server` cause they aren't json serializable
Tests:
```
deepsparse.server --task image_classification --model_path "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned85_quant-none-vnni"
```
Docs:
=> Remove: `numpy.ndarray` from ImageClassification schema

src/deepsparse/server/main.py
Tested:
- `deepsparse.server --task question_answering`
- `deepsparse.server --task question-answering`
- `deepsparse.server --task Question_Answering`
- `deepsparse.server --task Question-Answering`
=> Enabling hyphenated task names in deepsparse.server

src/deepsparse/transformers/pipelines/mnli_text_classification.py
This cherry pick has two commits. First adds a couple value errors that trigger when the pipeline is initialized, the second adds parenthesis around brackets in a string to make it clear that the brackets should be raw text, not formatted.
=> Cherry pick: argument checks for hypothesis template and nli indexes

src/deepsparse/image_classification/schemas.py
Cherry Pick for PR #560 
Remove: `numpy.ndarray` ImageClassification schema to work with `deepsparse.server`
=> Remove: `numpy.ndarray` ImageClassification schema 

tests/deepsparse/transformers/test_helpers.py
A bert model that was being used for unit testing got updated, so the onnx node names have changed. https://github.com/neuralmagic/zoomodels/pull/425. This is confirmed to happen for minor changes to onnx models.
=> Updated bert unit tests

src/deepsparse/transformers/helpers.py, tests/deepsparse/transformers/test_helpers.py
tokenizer_config.json is needed to define special characters in the tokenizer (as opposed to tokenizer.json used for determining tokenizer class).  future refactor will make deployment directory a first class citizen across all pipelines without casework for any files. This PR adds support for downloading the tokenizer_config file in the manual parsing of the deployment directory
**test_plan:**
tested manually with https://github.com/neuralmagic/sparsezoo/pull/215 in env. all 3 deployment files correctly downloaded and used to load tokenizer
=> force download of tokenizer_config.json when available

setup.py, src/deepsparse/transformers/haystack/__init__.py, src/deepsparse/transformers/haystack/haystack_reqs.txt, tests/deepsparse/transformers/__init__.py
This PR reverts the changes made in https://github.com/neuralmagic/deepsparse/pull/532. It was found that installing Haystack dependencies through extras was not feasible. Haystack requires HF transformers as a dependency. However, having HF transformers breaks the auto install of NM transformers, as there is no good way to dynamically reload modules in python. There is also no good way to install Haystack in extras without installing its dependencies.
Given these blocks, reverting back to dynamical install fixes these issues by controlling which dependencies are need by Haystack through a requirements.txt file. We can then remove HF transformers from this dependency list, thus avoiding the issue of dynamic module reload.
=> Revert Haystack to Auto Install

tests/deepsparse/transformers/test_helpers.py
A bert model that was being used for unit testing got updated, so the onnx node names have changed. https://github.com/neuralmagic/zoomodels/pull/425. This is confirmed to happen for minor changes to onnx models.
https://github.com/neuralmagic/deepsparse/pull/571
=> Updated bert unit tests (#571)

setup.py, src/deepsparse/transformers/haystack/__init__.py, src/deepsparse/transformers/haystack/haystack_reqs.txt, tests/deepsparse/transformers/__init__.py
This PR reverts the changes made in https://github.com/neuralmagic/deepsparse/pull/532. It was found that installing Haystack dependencies through extras was not feasible. Haystack requires HF transformers as a dependency. However, having HF transformers breaks the auto install of NM transformers, as there is no good way to dynamically reload modules in python. There is also no good way to install Haystack in extras without installing its dependencies.
Given these blocks, reverting back to dynamical install fixes these issues by controlling which dependencies are need by Haystack through a requirements.txt file. We can then remove HF transformers from this dependency list, thus avoiding the issue of dynamic module reload.
https://github.com/neuralmagic/deepsparse/pull/556
=> Cherry pick: Revert Haystack to Auto Install (#556)

src/deepsparse/transformers/haystack/nodes.py, src/deepsparse/transformers/pipelines/embedding_extraction.py
It was noticed that Tevatron embeds the passage title into the raw text input. This PR adds that functionality to the DeepSparseDensePassageRetriever as an argument embed_title, which allows a user to generate passage embeddings with embedded titles. This argument is also implemented in the Haystack version of this class.
https://github.com/neuralmagic/deepsparse/pull/544
=> Add embed_title arg to DPR (#544)

tests/deepsparse/transformers/__init__.py
Haystack auto-install was causing failing tests due to a missing torch dependency.
https://github.com/neuralmagic/deepsparse/pull/581
=> Cherry pick 1.1 remove haystack install test

src/deepsparse/yolo/pipelines.py
YOLO pipelines would fail when a batch of `numpy.ndarray` is passed as input;
The bug is caused due to line 195 `cv2.resize(...)`
cv2 can only resize one image at a time, this PR adds an assumption that a batch of `numpy` arrays always is of the correct input size (else they couldn't be stacked into a batch). 
The changes were tested with sparseml.yolov5.val_onnx and with a server locally as follows:
```bash
sparseml.yolov5.val_onnx --model_path /home/rahul/models/yolo/best.onnx --data coco128.yaml
val_onnx: data=../sparseml/src/sparseml/yolov5/data/coco128.yaml, model_path=/home/rahul/models/yolo/best.onnx, batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.6, task=val, device=, workers=8, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, …
```
=> [Bugfix] Assume a batch of numpy arrays is of the correct input shape

setup.py, src/deepsparse/transformers/haystack/__init__.py, src/deepsparse/transformers/haystack/haystack_reqs.txt
This PR moves all farm-haystack dependencies to setup.py under deepsparse[haystack]
https://github.com/neuralmagic/deepsparse/pull/597
=> Move farm-haystack deps to deepsparse[haystack] (#597)

setup.py
Because click~=8.0.0 is explicitly not allowed by wandb, this PR allows minor version updates to click.
Tested by installing with dev dependencies (black). Because there are no click commands in deepsparse, there were no commands to test.
=> Relax click dependency (#611)

tests/deepsparse/image_classification/test_pipelines.py, tests/deepsparse/pipelines/test_async_pipeline.py, tests/deepsparse/pipelines/test_custom_pipeline.py, tests/deepsparse/pipelines/test_dynamic_batch_pipeline.py, tests/utils/__init__.py, tests/utils/engine_mocking.py, tests/utils/test_engine_mocking.py
This adds a feature to patch `LIB.deepsparse_engine()` with our own fake class that reads onnx models and returns numpy arrays in the expected shape.
This will enable unit tests to avoid expensive compiles, however they will still download the `.onnx` files.
=> Adding `@mock_engine()` to avoid compiling models in tests

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/embedding_extraction.py, src/deepsparse/transformers/pipelines/pipeline.py, src/deepsparse/transformers/pipelines/question_answering.py, src/deepsparse/transformers/pipelines/text_classification.py, src/deepsparse/transformers/pipelines/token_classification.py, src/deepsparse/transformers/pipelines/zero_shot_text_classification.py, tests/deepsparse/pipelines/test_bucketing.py
Previously transformer models calculated the input sequence length based on the direct output of tokenizers. However the output of tokenizers is a dict that looks like this:
```python
>>> p.tokenizer(["hello", "hello my name is", "test one two three, this is a long one"], add_special_tokens=True, return_tensors="np", padding=False, truncation=False)
{'input_ids': array([list([101, 7592, 102]), list([101, 7592, 2026, 2171, 2003, 102]),
list([101, 3231, 2028, 2048, 2093, 1010, 2023, 2003, 1037, 2146, 2028, 102])],
dtype=object), 'token_type_ids': array([list([0, 0, 0]), list([0, 0, 0, 0, 0, 0]),
list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])], dtype=object), 'attention_mask': array([list([1, 1, 1]), list([1, 1, 1, 1, 1, 1]),
list([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])], dtype=object)}
```
This …
=> Fixing seq length calculation for transformers and testing

src/deepsparse/image_classification/pipelines.py, src/deepsparse/yolact/pipelines.py, src/deepsparse/yolo/pipelines.py
As part of #604, preprocessing was moved out of async threadpool execution. This PR changes the CV pipelines (image classification, yolo, yolact), to use `Pipeline.executor` in their preprocessing scripts. This is a performance improvement for static batch, because previously async preprocessing was not done for static batch.
Note: This only makes a difference when the pipelines need to load images. If pipelines receive all numpy arrays, then there is no performance gain when using async preprocessing.
=> Using executor in cv pipeline preprocessing

tests/deepsparse/pipelines/test_pipeline.py
time.time_ns() was added in python 3.7, so reverting for 3.6 support
=> Using time.perf_counter() instead of time.time_ns()

src/deepsparse/pipelines/numpy_schemas.py, tests/deepsparse/pipelines/test_numpy_schemas.py
Currently in our code we have to use `Any` or specify arbitrary_types_allowed in our pydantic schemas. Additionally fastapi crashes when you have a numpy array type or have arbitrary_types_allowed specified.
This PR adds `NumpyArray` to address this. Follow on PRs will be made to switch existing schemas to use this class.
See docstring and tests for examples
=> Adding numpy compatible pydantic schemas

src/deepsparse/server/README.md
They were messing up github README viewer before.
=> Escape sub backticks in server readme

src/deepsparse/server/config.py
This was missing from the new EndpointConfig. The kwargs are basically just passed to PipelineConfig.kwargs
=> Adding kwargs into EndpointConfig

src/deepsparse/server/README.md
this is the only supported QA compiled batch size so docs currently fail. dynamic batch enables higher batch sizes to be run
=> server documentation - set QA batch size to 1

src/deepsparse/pipeline.py
Moving to use `self.executor.map` for consistency with preprocessing. Internally executor.map does the same thing.
=> Small readability improvement for Pipeline.__call__

src/deepsparse/yolo/README.md, src/deepsparse/yolo/pipelines.py, src/deepsparse/yolo/schemas.py
This field just contains what all the other fields in the output contains, so its very redundant. 
Unit tested and searched codebase for any use of "predictions"
=> Removing predictions from YOLOOutput

src/deepsparse/server/config.py, src/deepsparse/server/server.py, tests/server/test_endpoints.py
Both of these values are very useful to tuning server performance. torch.set_num_threads(1) is a good default to make sure torch isn't contending with engine. threading pinning to cores for engine is enabled by default as well.
Tested with unit tests.
=> Adding thread pinning and torch.set_num_threads to ServerConfig

src/deepsparse/loggers/prometheus_logger.py, src/deepsparse/server/helpers.py, tests/server/test_helpers.py
utility functions for instantiating loggers - main contribution is the ability to specify and instantiate loggers from a simple yaml config. yaml config should be the integration name followed by it's init kwargs
example config:
```yaml
prometheus:
port: 8001
text_log_save_dir: /home/deepsparse-server/prometheus
text_log_save_freq: 30
```
**test_plan:**
pytest included
=> [deepsparse.server] utility functions for instantiating loggers

tests/server/test_app.py, tests/server/test_endpoints.py
This has no actual changes in it, just separating out _build_app tests from endpoint tests.
test plan: unit tests
=> Reorganize tests/server/ by splitting out _build_app tests

examples/README.md, examples/google-kubernetes-engine/Dockerfile, examples/google-kubernetes-engine/README.md, examples/google-kubernetes-engine/sample-config.yaml, examples/google-kubernetes-engine/server-config.yaml
Adds link to GKE tutorial on how to deploy a dockerized web server to GKE. I don't think we should duplicate this information in our repo's readme because:
1. The GKE tutorial has a TON of useful commands/help.
2. It makes it explicit that we don't require anything special to run on GKE. This means users with GKE experience already don't need to read through our README just to find out that we are using normal GKE commands.
3. Any docs duplicated here may become out of date.
test plan: built and ran docker image locally
=> Adding GKE to examples

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/mnli_text_classification.py, src/deepsparse/transformers/pipelines/zero_shot_text_classification.py, tests/deepsparse/transformers/pipelines/test_mnli_text_classification.py
This PR updates the zscp pipeline to account for new [dynamic batch](https://github.com/neuralmagic/deepsparse/pull/604). This includes
* Removing now unnecessarily error checks that constrain acceptable batch sizes
* Removing engine_forward logic that groups inferences by label
* Adding a check for divisible batch sizes (a little redundant given that the pipeline base class has a similar error, but this one makes it explicitly clear that the number of samples is the product of num_labels and num_sequences
* Adding tests to check correct pipeline instantiation
I've validated using the aformentioned tests as well as `eval_downstream` on sst2.
``` bash
deepsparse.transformers.eval_downstream zoo:nlp/text_classification/bert-base/pytorch/huggingface/mnli/12layer_pruned90-none -d sst2 …
```
=> Zscp: Full dynamic batch, remove batch size checks

setup.py, src/deepsparse/lib.py, src/deepsparse/license.py
script for validating a deepsparse commercial license
documentation included in #647
tested by @tlrmchlsmth  - valid license write to default config dir, invalid license errors out, valid license write to env var overwritten config dir, `compile_model` splash message displays enterprise info for valid written license
**example success**
```bash
$ deepsparse.license valid-license.txt
2022-09-15 10:30:08 __main__     INFO     DeepSparse license successfully validated
2022-09-15 10:30:08 __main__     INFO     DeepSparse license file written to /home/benjamin/.config/neuralmagic/license.txt
```
we verify that enterprise edition is enabled with the splash message below:
```python
>>> from deepsparse import image_classification_pipeline
>>> pipeline = image_classification_pipeline()
DeepSparse …
```
=> deepsparse.license script - add commercial license file from jwt token

tests/deepsparse/transformers/pipelines/test_mnli_text_classification.py
nullcontext doesn't exist in python 3.6
=> Removing nullcontext from tests

src/deepsparse/image_classification/validation_script.py
currently, the eval script is missing a call to unwrap the inner layer of a batch prediction for IC eval. Can look into unwrapping this list at pipeline level later.
This caused accuracy to crash to 0 for runs with batch size > 0. after this fix running accuracy returns to expected:
```
$ deepsparse.image_classification.eval --model-path zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/base-none --dataset-path /home/benjamin/data/imagenet/val --batch-size 64
2%|█▎                                                                  | 15/781 [00:08<07:05,  1.80it/s, Running Accuracy=89.27%]
```
=> [cherry-pick] [image-classification] fix IC eval script bug for batch size > 0 (#659)

setup.py, src/deepsparse/license.py
* expose validate_license to python API
* add optional pathway to validate, take out log
* add validate_license CLI
* add support to print any returned splash message in true validate mode
=> [cherry-pick] expose validate_license to python API (#665)

src/deepsparse/server/config.py
This makes it so prometheus server is only spun up when specified.
Testing: unit tests
=> Setting ServerConfig.loggers default to None

setup.py, src/deepsparse/license.py
validate_license included click decorators to expose it as a top level deepsparse cli, however this makes use of it less flexible when called via python API (ie in the license script) as click type checking is added (currently causes issues with tempfiles).
this PR adds a simple fix to move out the cli entrypoint to its own function keeping the helper standalone.
**test_plan**
license functionality internally tested by QA
=> [license] fix - move validate_license cli to its own function

src/deepsparse/license.py
currently if a user sets `NM_CONFIG_DIR=""` `/` will be used as the config dir, similar unexpected behavior may happen for other improper ways of unsetting the env variable. This PR adds a quick fix to evaluate the `NM_CONFIG_DIR` value before assigning a default (`get` will only default the value if it is properly unset)
**test_plan**
license testing currently done internally
=> use default license config dir used when NM_CONFIG_DIR evals to False

src/deepsparse/license.py
currently if a user sets `NM_CONFIG_DIR=""` `/` will be used as the config dir, similar unexpected behavior may happen for other improper ways of unsetting the env variable. This PR adds a quick fix to evaluate the `NM_CONFIG_DIR` value before assigning a default (`get` will only default the value if it is properly unset)
=> [cherry-pick] use default license config dir used when NM_CONFIG_DIR evals to False

tests/deepsparse/loggers/test_prometheus_logger.py, tests/helpers.py, tests/server/test_endpoints.py, tests/server/test_helpers.py, tests/server/test_prometheus.py
This fixes port in use errors during the unit tests cause by fixed port numbers.
Test plan: unit tests
=> Setting all ports to dynamic ports in unit tests

tests/server/test_hot_reloading.py
In python 3.7 MagicMock.call_args is a tuple (https://docs.python.org/3.7/library/unittest.mock.html#unittest.mock.Mock.call_args)
In python 3.8+ call_args had .args and .kwargs introduced, but also supports tuple destructuring. (https://docs.python.org/3.8/library/unittest.mock.html#unittest.mock.Mock.call_args)
This PR reverts usage of call args back to 3.7 compatible version
=> Using py37 compatible call args in unit tests

src/deepsparse/license.py
**test_plan**
QA to check this passes expected flow
=> always print splash message for deepsparse.validate_license_cli regardless of input

src/deepsparse/transformers/pipelines/text_classification.py
adds support for multi label text classification inference with the following changes (matching transformers repo pipeline)
* adds a `top_k` arg for specifying number of labels to return
* adds logic to deprecate `return_all_scores`
* runs sigmoid instead of softmax when model config is set to `multi_label_classification` mode
**test_plan**
manual for now, further testing to be added in pipelines unit tests work. ran eval_downstream against existing qqp and sst2 models, verified expected number of outputs returns for various top_k values
=> multi label support for text classification pipeline

src/deepsparse/server/cli.py
This adds support for using the old version of deepsparse.server cli with a deprecation message:
```
deepsparse.server --task qa
deepsparse.server task qa
deepsparse.server --config_file /some/path
deepsparse.server config /some/path
```
Test plan:
- Since this is not replacing the new way of the api, none of the QA or unit tests need to be updated
- Unit tests
- Manual cli testing
=> Adding backwards compatibility for server cli

examples/aws-sagemaker/endpoint.py
deleting`Session` region call and instead passing in the hardcoded region name. It seems to cause a bug.
=> sagemaker bug fix

src/deepsparse/license.py
changes:
* adds python API wrapper for `license_status`
* updates `validate_license` to call into `license_status` as source of truth
* warning messages no longer displayed on first call to validate for `deepsparse.license`
**test_plan**
manual from QA after engine build/cherry-pick
=> [license] support for non-throwing license_status call

setup.py
This ensures that the licenses included under deepsparse/src/deepsparse during build are included in the python package when it is built.
=> Adding licenses folder to package data

setup.py
Cherry Pick for https://github.com/neuralmagic/deepsparse/pull/730
=> [Cherry Pick] Do not include the `LICENSE-NEURALMAGIC` file in the `deepsparse-ent` installation folder

examples/sparsestream/README.md
adding context to the README highlighting to users that they need to add their own API tokens to the config file.
=> Sparsestream quick fix

setup.cfg, setup.py
Since licenses will be at top level instead of src/deepsparse level, this adds support for copying all licenses into <package>-dist-info directory when installed.
I.e. this is the contents of the dist info directory after install:
```bash
lib/python3.9/site-packages/deepsparse_nightly-1.2.0.20221101.dist-info/
total 124
drwxrwsr-x  2 corey corey  4096 Nov  1 15:20 ./
drwxrwsr-x 43 corey corey  4096 Nov  1 15:20 ../
-rwxrwxr-x  1 corey corey  1338 Nov  1 15:20 boost.license*
-rw-rw-r--  1 corey corey   856 Nov  1 15:20 entry_points.txt
-rwxrwxr-x  1 corey corey  1461 Nov  1 15:20 fmath.license*
-rw-rw-r--  1 corey corey     4 Nov  1 15:20 INSTALLER
-rwxrwxr-x  1 corey corey  1076 Nov  1 15:20 json.license*
-rwxrwxr-x  1 corey corey  1075 Nov  1 15:20 jwt-cpp.license*
-rwxrwxr-x  1 corey …
```
=> Moving licenses from setup.py to setup.cfg

setup.cfg, setup.py
* Moving licenses from setup.py to setup.cfg
* Adding src/deepsparse/licenses/* to setup.cfg
=> [Cherry pick] Moving licenses from setup.py to setup.cfg (#738)

src/deepsparse/transformers/pipelines/embedding_extraction.py
This is because the stub was updated to have 12layer removed
=> Updating default embedding extraction stub

src/deepsparse/transformers/pipelines/token_classification.py
NER has labels of the letter 'O' for words which are not labelled as something, the current pipeline uses the digit zero ('0') instead of the letter 'O'.
=> Fix default ignore labels in token classification

src/deepsparse/image_classification/annotate.py, src/deepsparse/utils/__init__.py, src/deepsparse/yolact/annotate.py, src/deepsparse/yolo/annotate.py
By default we don't install opencv, so right now anything that imports from utils will try to import opencv and fail.
This will result in errors like:
```
numactl -N0 -m0 -C0-7 deepsparse.benchmark zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned95_obs_quant-none -s sync
File ".../nm-dev/bin/deepsparse.benchmark", line 5, in <module>
from deepsparse.benchmark.benchmark_model import main
File ".../nm-dev/lib/python3.9/site-packages/deepsparse/__init__.py", line 33, in <module>
from .engine import *
File ".../nm-dev/lib/python3.9/site-packages/deepsparse/engine.py", line 27, in <module>
from deepsparse.benchmark import BenchmarkResults
File ".../nm-dev/lib/python3.9/site-packages/deepsparse/benchmark/__init__.py", line 17, in <module> …
```
=> Remove import deepsparse/utils/annotate.py from utils/__init__.py

src/deepsparse/transformers/eval_downstream.py
this PR adds support for squad_v2 in the transformers eval_downstream script
**test_plan:**
@anmarques verified accuracy against a squad_v2 model
=> squad_v2 eval support

setup.py
fastapi dropped httpx as a dependency and has a few other dependency changes causing issues in `0.87`. this PR restricts the max supported fastapi version to resolve these and unblock development. future work should reconcile dependencies to support later versions.
**test_plan:**
GHA tests now passing
=> restrict max fastpi version

src/deepsparse/loggers/function_logger.py, src/deepsparse/loggers/helpers.py, src/deepsparse/server/build_logger.py, src/deepsparse/server/config.py, tests/deepsparse/loggers/test_helpers.py, tests/server/test_build_logger.py
Currently, for a log to be propagated, the user must add a function logger definition for it in the endpoint config
By default, we would like to enable the logging of all pipeline system logs (right now this includes just the base timings recorded by the pipeline). This PR enables the propagating of these logs with the following changes:
1) support for a new identifier pattern `category:<CATEGORY>` which matches to any log of a given `MetricCategories` value
2) adding a function logger in build loggers that matches to `category:system` and passes these logs through on each call with an `identity` function
future work will enable the user to disable specific or all system logs via the config, logic for this may be added through updates to `_create_system_logger`
**test_plan**:
unit tests …
=> [data-logging] support server default logging of all pipeline 'SYSTEM' logs

src/deepsparse/server/build_logger.py, src/deepsparse/server/helpers.py, tests/deepsparse/loggers/helpers.py, tests/server/test_build_logger.py
Allows the user to specify their custom leaf loggers to use in the server.
First, the user needs to specify the path to the custom logger in the yaml config:
```yaml
num_cores: 2
num_workers: 2
loggers:
custom_logger:
path: tests/deepsparse/loggers/helpers.py:CustomLogger
arg1: 1
arg2: some_string
endpoints:
- task: question_answering
route: /unpruned/predict
model: zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/base-none
```
Then, the logic of `build_logger` function will attempt to instantiate the `custom_logger`.
- will look for module `tests/deepsparse/loggers/helpers.py`
- try to import `CustomLogger` from the module
- instantiate the `CustomLogger` with the specified arguments
- finally, it will also check whether `CustomLogger` inherits from our internal …
=> [Data Logging] Custom Logger

src/deepsparse/loggers/__init__.py, src/deepsparse/loggers/async_logger.py, src/deepsparse/server/build_logger.py, tests/deepsparse/loggers/helpers.py, tests/deepsparse/loggers/test_async_logger.py, tests/server/test_build_logger.py, tests/server/test_prometheus.py
basic implementation for a `AsyncLogger` that submits logging jobs that do not block the main process.
current implementation uses a threadpool, however should further evaluate tradeoffs with process pool, and potential future need for a more sophisticated job worker
open questions:
* how to best propagate errors after jobs have been submitted and user requests have been returned. currently issuing a python `error` log that displays the error message however this is more of a "silent" failure which is not ideal - a separate job worker may be able to better handle this
* exploration of limitations of executors and potential overhead added
**test_plan:**
included tests to verify that calls are non blocking, numpy arrays and functions may be submitted, verification of job run and error …
=> [data-logging] AsyncLogger implementation

src/deepsparse/utils/extractor.py
fixes a bug found by @mgoin where a line of code references a property added by onnx 1.10. Deepsparse support lower versions, this PR adds a check
=> [bug-fix] model extractor suport for onnx < 1.10

src/deepsparse/transformers/pipelines/zero_shot_text_classification.py
the task attribute is generally assigned to pipeline classes at registration time, however since the zero shot pipeline routes the creation of new classes to a child class, the child class is not assigned their registered task name. this leads to an immediate error when the pipeline's task attribute is accessed during logging.
this pr assigns the task to the wrapped class
**test_plan:**
unit tests for mnli text classificaiton pipeline now passing on top of logging feature branch
=> [zero_shot_classification] assign task to wrapped zero shot pipeline class

setup.cfg, setup.py
Including as much detail here for future purposes.
I'm not sure why this suddenly stopped working or even worked in the first place.
1. Sample setup.cfg file here: https://github.com/pypa/sampleproject/blob/main/setup.cfg, however it only lists one entry in license_files
2. https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file details the license_files fields with this example (note the newline delimited values.)
```cfg
[metadata]
license_files =
license.txt
3rdparty/*.txt
```
3. https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#metadata has a table of metadata. the license_files row has the entry `list-comma`, which I take to also mean commas are accepted.
4. The values in setuptools are actually populated on this …
=> Moving license_files to setup.py from setup.cfg

setup.py
When is_enterprise flag is set, the METADATA file now looks like:
```
Metadata-Version: 2.1
Name: deepsparse-ent
Version: 1.3.0
<snip>
License: Apache
<snip>
```
=> Changing license when build is enterprise

src/deepsparse/benchmark/benchmark_model.py
deepsparse.benchmark logs a message warning about a default value of num_streams when passed `-s sync`. This should be getting short-circuited by a check in `parse_num_streams`, but it's checking for a value of "single_stream" instead of "singlestream"
=> Fix num_streams info message suppression

src/deepsparse/loggers/prometheus_logger.py, src/deepsparse/server/build_logger.py, tests/server/test_build_logger.py, tests/server/test_loggers.py
Reported by @rsnm2 : https://app.asana.com/0/1203146234476221/1203483881614817/f
Prometheus collects metrics in the form o of integers/floats and does not digest any complex data types such as lists, tuples, or arrays. 
Before I implemented a quick fix to account for values such as `np.array([3])`, s.t Prometheus can log it as `3`. 
However, since not only NumPy arrays have an attribute `is_integer` but python ints/floats, as well, the logic was rounding up all the values to the full integers.
I decided not to account for edge cases and not add any additional if statements to the `_validate` method. Accounting for different exceptions feels a bit hacky and dangerous. We should reserve `PrometheusLogger` for metrics (floats/ints) only, as this is an implicit assumption when one uses …
=> [Fix] Prometheus Logger logging all zeros for latency metrics

src/deepsparse/utils/onnx.py
fixes an issue where extracted layers who were unable to be issued shape inference (any non trivial node) with the onnx shape inference API would have improper tensor type shapes set causing an unnecessary crash with the onnx checker
**test_plan:**
* unit tests passing
* manually verified fix across multiple domains and models
=> [cherry-pick][EmbeddingExtraction][fix] clear 'None' shapes from uninfered extracted onnx outputs

src/deepsparse/utils/onnx.py
fixes an issue where extracted layers who were unable to be issued shape inference (any non trivial node) with the onnx shape inference API would have improper tensor type shapes set causing an unnecessary crash with the onnx checker
**test_plan:**
* unit tests passing
* manually verified fix across multiple domains and models
=> [EmbeddingExtraction][fix] clear 'None' shapes from uninfered extracted onnx outputs

src/deepsparse/utils/onnx.py
`graph_output_name` previously was not set when `emb_extraction_layer` was a str
**test_plan:**
manually verified
=> [EmbeddingExtraction] fix graph output assignment in str extraction layer targets

setup.py
New `black` version is messing up our tests. Let's pin the version to the latest, compliant one for now.
=> Pin black version

src/deepsparse/loggers/helpers.py, tests/deepsparse/loggers/test_helpers.py
One of the requirements for 1.4 is:
`Support [:,:0] slicing in the configuration file for identifiers`. 
This is essentially support for slicing/indexing data identifier properties that are numpy arrays or torch tensors (N-dimensional data structures) in the context of DeepSparse server data logging.
After consultation with @rsnm2 we have decided to drop this feature. This is my logic behind the decision:
----> from my convo with Rob:
Let me show by example why numpy slicing in our context is pretty difficult:
Imagine this operation:
```python
array = numpy.randn(10,10,3) # creates random array with dims: (10,10,3)
array_sliced = array[:1,:1,0] 
```
Now If we did this in the context of our repo, we would apply slicing as a sequence :1 -> :1 -> 0
This would mean:
```python
array = …
```
=> [System Logging] Raise warning when attempting to slice/index arrays or torch

src/deepsparse/benchmark/benchmark_model.py, src/deepsparse/benchmark/benchmark_sweep.py
This PR will add support to load a Engine Dynamically from a user specified python script
In the `benchmark_sweep` and `deepsparse.benchmark` utility now users can specify a custom engine class, that will be dynamically loaded during runtime. A possible use case could be to benchmark different Inference backends.
Note: If the graph is not in `onnx` format then the engine classes must specify a function `generate_random_inputs` that takes in a batch size and returns inputs for the model in an ingestable format. A better solution could be to force this contract by creating a base class. But have left this as is for now
=> Dynamic Engine Load

src/deepsparse/server/server.py
To resolve issue of
```python
File "/home/ubuntu/workspace/Github/TestDeepsparse/runtests/lib/python3.8/site-packages/deepsparse/server/server.py", line 266, in _predict
system_logging_config=params.get("system_logging_config"),
AttributeError: 'Depends' object has no attribute 'get'
```
Ran commands in yolo README.md
=> Using system_logging_config directly instead of using Depends

src/deepsparse/image_classification/pipelines.py
PIL reads PNG images as RGBA by default, causing an error later on in the pipeline as all images are assumed to have three channels. This PR makes sure that whatever is being returned by PIL, has 3 dimensions
Testing:
- manually tested the result of the pipeline for an input JPG image (the result does not change after introducing this PR)
- made sure that the PNG image gets properly inferred (the image below results in top 3 labels `labels=["banana", "orange", "lemon"]`)![image](https://user-images.githubusercontent.com/97082108/213651151-9f5a846f-89e2-4e8a-b216-e1cadec037b2.png)
=> IC pipeline to accept PNG images

setup.py
There are issues with the latest opencv-python as you can see in https://github.com/opencv/opencv-python/issues/772.
This PR pins opencv-python to the last working version, as suggested in the above PR.
Ran pip install before this PR to verify that opencv `4.7.0.68` is installed, and after this PR `4.6.0.66` is installed.
=> pin opencv-python==4.6.0.66

src/deepsparse/yolo/annotate.py
This PR adds in support to override onnx graph shape for yolo annotation flow:
The update needed two minor changes:
- Accepting a 2 integer tuple representing image shape to override model input shapes with; added `--model_input_shape` cli argument for that
- Propagating the new model input shape to the yolo pipeline constructor via the `image_size` argument; the actual code to override the shapes is already in place in the YOLO pipeline.
Command:
```bash
deepsaprse.object_detection.annotate \
--source ./tests/deepsparse/pipelines/sample_images/basilica.jpg \
--save-dir /home/rahul/projects/deepsparse/results \
--model_input_shape 1280 1280
```
A breakpoint was set after pipeline creation and the model shape was checked to conform with the passed in `--model_input_shape`
=> Update: Yolo Annotation to allow shape overrides

src/deepsparse/loggers/metric_functions/computer_vision/built_ins.py, src/deepsparse/loggers/metric_functions/natural_language_processing/built_ins.py, src/deepsparse/loggers/metric_functions/natural_language_processing/token_classification/built_ins.py, src/deepsparse/loggers/metric_functions/utils.py, tests/deepsparse/loggers/metric_functions/computer_vision/test_built_ins.py, tests/deepsparse/loggers/metric_functions/natural_language_processing/token_classification/built_ins.py
For the sake of clarity, we want to move away from collecting the information derived from batches of data in a dictionary. Instead, let's collect them inside the `BatchResult` object (which we can further refer to inside the leaf loggers).
So instead of e.g. keeping label of each image in the batch in a dictionary like:
`{"0": "duck, "1": "rabbit", "2": "platypus", ... }`,
we use:
`BatchResult(["duck", "rabbit", "platypus", ...])`
Handing the `BatchResult` object within the leaf loggers will be handled in a separate PR.
=> [MLOps 1.5] Add `BatchResult` object to hold list-like values for logging

.github/workflows/local-install-check.yaml
the version of `python-distro-info`installed in by GHA tests has a version that causes a crash when installing with our local develop mode install test.
until the version is updated, running the test in a virtual environment (this is our recommended flow anyways) which will not have visibility to the global install with the bad version.
see this issue for more information: https://github.com/pypa/setuptools/issues/3772
**test_plan:**
GHA `local-install-test` now passing
=> temporary fix for local-develop-test GHA failure

src/deepsparse/loggers/constants.py, src/deepsparse/loggers/prometheus_logger.py, src/deepsparse/pipeline.py, src/deepsparse/server/system_logging.py
At the current state, manipulating and moving around the system group names is a bit tedious. This is because they exist as separate values. This PR wraps them inside a `dataclass` object.
=> [MLOps 1.5] Refactor the constants that contain a set of `SystemGroups`

src/deepsparse/transformers/eval_downstream.py
fixes a bug where outputs ignored by the default `ignore_labels` value would cause a size mismatch with the expected labels length during metrics computation
**test_plan:**
verified manually. research team to QA
=> [transformers] do not ignore any labels in conll eval pipeline

src/deepsparse/benchmark/benchmark_model.py, src/deepsparse/benchmark/benchmark_sweep.py
This PR includes a few bugfixes to benchmark-sweep script for ease of use + generating random inputs for custom engine use case. 
Major changes include:
- Check and generate random inputs from the instantiated model over engine class
- Add: Support for loading files with any extension, for cases where a custom file type is to be benchmarked
- Add: click context settings to avoid confusion b/w underscores vs hyphens + some other good defaults
- Update: export csv name to not include the extension of model, by using `Path(...).stem` over `Path(...).name`
- Fix: batch_size and num_core ingestion in case a trailing comma is provided with their values
Tests:
```bash
deepsparse.benchmark_sweep \
--model-paths /home/rahul/resnet_v2_101_1_default_1.custom_ext \
-e …
```
=> Bugfixes: benchmark-sweep

setup.py, src/deepsparse/open_pif_paf/README.md, src/deepsparse/open_pif_paf/annotate.py
The Open Pif Paf callables in `setup.py` were pointing to incorrect location this PR fixes that, and also adds `--model_filepath` in example commands, (it is required)
=> Update: Open Pif Paf callables

examples/ultralytics-yolov8/README.md
the examples directory was removed when the integration was productionized. moving forward going to standardize to updating example directories to point to the src/ documentation rather than removing completely
=> [YOLOv8] re-add examples directory with pointer to src/deepsparse docs

src/deepsparse/yolact/annotate.py, src/deepsparse/yolact/pipelines.py, src/deepsparse/yolact/utils/annotate.py, src/deepsparse/yolact/utils/utils.py
This PR refactors the YOLACT pipeline. Noteworthy changes:
- endow the pipeline with the ability to resize the output masks and bounding boxes so that they correspond to the original image size (reimplementation of the functionality introduced by @rahul-tuli to the YOLO pipeline)
- removing the `_resize_to_fit_img` function from the yolact annotation function. The motivation here is to make `src/deepsparse/yolact/utils/annotate.py` annotation function easily handle both YOLACT and YOLOv8Seg outputs. In the future, when the long-awaited refactor of CV pipelines happens, we could hopefully use this function to annotate any object/instance segmentation models.
Testing:
```bash
deepsparse.instance_segmentation.annotate  --source src/deepsparse/yolact/sample_images/thailand.jpg
```
=> [YOLOv8-Seg] Refactor YOLACT annotation and pipeline

src/deepsparse/yolo/pipelines.py, src/deepsparse/yolo/schemas.py, src/deepsparse/yolov8/pipelines.py, src/deepsparse/yolov8/schemas.py
Adding a few functionalities:
- enabling YOLO/YOLOv8 to return intermediate outputs
- handling the corner case in the YOLOv8 segmentation pipeline, when no detection is made.
=> [YOLOv8-Seg] Tiny refactor of YOLO and YOLOv8 pipelines

src/deepsparse/open_pif_paf/pipelines.py, src/deepsparse/open_pif_paf/schemas.py
```python
input = "src/deepsparse/yolo/sample_images/basilica.jpg"
pipeline = Pipeline.create(task="open_pif_paf", model_path="openpifpaf-resnet50.onnx", return_cifcaf_fields=True)
output = pipeline(images=input)
```
OpenPifPaf is comprised of two algorithms.
- prediction of CifCaf fields (using a parametrized neural network)
- matching CifCaf fields to actual poses (using a deterministic, algorithm)
I would like to give users an option not only to receive decoded poses (final representation) but also to fetch CifCaf fields (intermediate representation).
The motivation is for easy validation (my validation use case) or the ability to use the pipeline as a component of a larger system (that requires the CifCaf fields and not necessarily the decoded poses).
=> [OpenPifPaf] Allow for returning CifCaf fields

src/deepsparse/image_classification/__init__.py
Right now deepsparse ic auto installs are broken:
Steps to reproduce
```bash
python3.8 -m venv test-venv
source test-venv/bin/activate
pip install deepsparse
deepsparse.image_classification.annotate --help
```
Relevant Traceback:
```bash
File "/home/rahul/test-venv/bin/deepsparse.image_classification.annotate", line 5, in <module>
from deepsparse.image_classification.annotate import main
File "/home/rahul/test-venv/lib/python3.8/site-packages/deepsparse/image_classification/annotate.py", line 72, in <module>
import cv2
ModuleNotFoundError: No module named 'cv2'
```
This PR fixes the error by auto-installing cv2 in IC `__init__.py` file
Noting that this is a quick temporary fix as eventually we will move away from autoinstalls and rely on …
=> [BugFix] Add  opencv to IC AutoInstalls

src/deepsparse/yolov8/pipelines.py
Fix to: https://app.asana.com/0/1203126676641557/1204132871838595/f
The solution to the following issue:
When exporting the detection ONNX model directly from ultralytics:
- the engine returns a single output 
When exporting the detection ONNX model from SparseML:
-  the engine returns four inputs (single output + three auxiliary inputs (outputs from the intermediate layers).
The most proper thing to do would be to standardize the output for both ONNX export pathways. My solution is less correct but should do the job 
Testing with ultralytics-exported model:
```bash
python src/deepsparse/yolov8/validation.py --model_path yolov8n.onnx
```
Output:
```bash
...
val: Scanning /home/ubuntu/damian/deepsparse/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: …
```
=> [Fix] Inconsistent number of engine outputs between ONNX models from ultralytics/sparseml export

.github/workflows/build-and-publish-tagged-images.yaml, docker/Dockerfile, docker/README.md
This push will revamp our docker infrastructure to
make it easier to start with deepsparse
The identified goals for now are as follows:
Overarching goals:
TODO:
Once Approved, remove current branch from event triggers, maybe also remove nightly builds
We can also use the specified dockerfile to build a dev container like the following:
```bash
docker build --target container_branch_dev --build-arg DEPS=dev -t deepsparse-dev-docker . && docker container run -it deepsparse-dev-docker bash
```
A successful GHA push on a dummy `release/99.99.96` branch: https://github.com/neuralmagic/deepsparse/actions/runs/4415921132/jobs/7739522073
~NOTE: GHA red due to #939~
=> Update Docker Infra

setup.py, src/deepsparse/debug_analysis.py, src/deepsparse/engine.py
This PR migrates existing `deepsparse.analyze` utility to `deepsparse.debug_analysis` namespace
Test:
```bash
deepsparse deepsparse.debug_analysis --help
usage: deepsparse.debug_analysis [-h] [-wi NUM_WARMUP_ITERATIONS] [-bi NUM_ITERATIONS] [-ncores NUM_CORES] [-b BATCH_SIZE]
[-ks KERNEL_SPARSITY] [-ksf KERNEL_SPARSITY_FILE] [--optimization OPTIMIZATION] [-i INPUT_SHAPES] [-q]
[-x EXPORT_PATH]
model_path
Analyze ONNX models in the DeepSparse Engine
positional arguments:
model_path            Path to an ONNX model file or SparseZoo model stub
optional arguments:
-h, --help            show this help message and exit
-wi NUM_WARMUP_ITERATIONS, --num_warmup_iterations NUM_WARMUP_ITERATIONS
The number of warmup runs that will be executed before the actual benchmarking
-bi NUM_ITERATIONS, …
```
=> Migrate analyze functionality to `deepsparse.debug_analysis`

setup.py, tests/server/test_loggers.py
Well, once in a blue moon, simple tests for server logging fail. I am moderately sure that this is because the test completes before the log "gets" (asynchronously) to the leaf logger. This is a very rare event, a flaky test should account for that.
I think that alternatively, we could put the "sleep" function before `_test_logger_contents(...)`, but I think that making the test flaky is more elegant.
=> [Fix] Make `test_logging_only_system_info` flaky

src/deepsparse/utils/onnx.py, tests/test_benchmark.py
Because the onnx model had at least one dynamic axis (batch, h,w), it was failing in the benchmarking logic.
I fixed the test plus added a warning to avoid using models with dynamic shapes in `generate_random_inputs`.
=> [Fix] Explicitly specify the shape for the benchmarking model

src/deepsparse/utils/onnx.py
Reverting this change, since it turned out that it breaks several pathways.
=> [Fix] Remove `ValueError` in `generate_random_inputs`

src/deepsparse/version.py, src/deepsparse/yolo/pipelines.py, src/deepsparse/yolo/utils/utils.py, tests/test_benchmark.py
This cherry pick combines:
https://github.com/neuralmagic/deepsparse/pull/964
https://github.com/neuralmagic/deepsparse/pull/965
https://github.com/neuralmagic/deepsparse/pull/967
And applies the net of them to 1.4 release
=> [Cherry Pick] Support for dynamic input YOLO models (1.4.2)

setup.py, src/deepsparse/analyze.py
This PR represents the base feature branch for `deepsparse.analyze`
Relies on SparseZoo `ModelAnalysis.create` diff: https://github.com/neuralmagic/sparsezoo/pull/281
And summary updates diff: https://github.com/neuralmagic/sparsezoo/pull/285
```bash
Usage: deepsparse.analyze [OPTIONS] MODEL_PATH
DeepSparse Performance analysis for ONNX models.
MODEL_PATH: can be a SparseZoo stub, or local path to a deployment-directory
or ONNX model
Examples:
- Run model analysis on resnet
deepsparse.analyze ~/models/resnet50.onnx
Options:
--compare TEXT                  A multi-arg comma separated list of model
paths to compare against; can accept local
path to an onnx model, a path to deployment
folder containing a onnx model, a SparseZoo
stub, or a previously run analysis yaml
file. No comparision is …
```
=> `deepsparse.analyze`

src/deepsparse/engine.py, tests/test_engine.py
Add a DebugAnalysisEngine subclass of Engine for doing debug analysis.  The internals of the engine have changed so that a model must be compiled for analysis instead of calling an "analyze" method on an existing model.
=> Make DebugAnalysisEngine subclass

src/deepsparse/analyze.py
This PR will dereference node names from performance results while running deepsparse:
Essentially changes will be two fold:
```bash
deepsparse.analyze ~/models/resnet50.onnx
```
Output: (BatchNorms replaced by parent convs)
Output before this PR:
```bash
023-04-14 10:05:47 __main__     INFO     Starting Analysis ...
INFO:__main__:Starting Analysis ...
2023-04-14 10:05:48 __main__     INFO     Analysis complete, collating results...
INFO:__main__:Analysis complete, collating results...
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.5.0.20230303 COMMUNITY | () (release) (optimized) (system=avx512, binary=avx512)
Node Timings for Benchmark # 1:
NODE_NAME                      AVG_RUNTIME                    
BatchNormalization_1           0.16 …
```
=> Dereferencing Node Names for analyze performance results

src/deepsparse/yolov8/utils/validation/helpers.py, src/deepsparse/yolov8/validation.py
Introducing changes from sparseml to deepsparse as well: https://github.com/neuralmagic/sparseml/pull/1520
Testing:
tested the validation pathways with/without the argument. Performing as expected.
=> [YOLOV8] Add`--datasets-dir` to yolov8 entrypoints

docker/Dockerfile
This PR updates the dockerfile to use
`CMD` over `ENTRYPOINT` to allow easier overriding of commands for users
for example
Now the `deepsparse.server` can be run directly with one command
```bash
docker container run -it -p 5543:5543 ghcr.io/neuralmagic/deepsparse:1.4.2 \
deepsparse.server --task image-classification
```
=> Update: Dockerfile

DEVELOPING.md
This PR updates missed references of python3.6 to python3.7
=> Update: old references of python3.6 --> 3.7

src/deepsparse/yolov8/utils/validation/deepsparse_validator.py
Using dataset-path triggers the override of the data entry w/ a path to a local file. This pathway leads to an internal path in a string format, wheareas pycocotools expects a Path object. This PR fixes this issue by always making this path a "Path" object.
Testing plan:
Tested by evaluating YOLOv8-s:
`deepsparse.yolov8.eval --model-path zoo:cv/detection/yolov8-s/pytorch/ultralytics/coco/base-none --dataset-yaml coco.yaml  --dataset-path ~/datasets/coco
`
=> Fix for using dataset-path w/ coco

src/deepsparse/benchmark/benchmark_model.py
`num_cores` is properly defaulted in the benchmark model CLI but not python API function call. this can cause errors with operating over the `None` default value in that scenario.
This PR adds a fix to provide a default when `None` is specified
=> default num_cores in `benchmark_model` fn

src/deepsparse/benchmark/benchmark_model.py
* default num_cores in `benchmark_model` fn
`num_cores` is properly defaulted in the benchmark model CLI but not python API function call. this can cause errors with operating over the `None` default value in that scenario.
This PR adds a fix to provide a default when `None` is specified
* quality
=> [cherry-pick] default num_cores in `benchmark_model` fn (#1018)

src/deepsparse/transformers/eval_downstream.py
This PR should address https://github.com/neuralmagic/deepsparse/issues/1016 by updating docs to specify that we expect a path to `model.onnx, tokenizer.json, config.json` instead of a path to `model.onnx` which throws an error.
=> Fix misleading docs for model_path

src/deepsparse/utils/onnx.py
The reason why the tests were failing is twofold:
1. the external data for the tensors was not saved in the same directory as the onnx model (`save_onnx_to_temp_files` function). Solution:
```python
external_data = os.path.join(
tempfile.tempdir, next(tempfile._get_candidate_names())
)
``` 
Before:
```python
shaped_model.name -> /tmp/i_am_a_model.onnx
external_data -> i_am_data
```
Now:
```python
shaped_model.name -> /tmp/i_am_a_model.onnx
external_data -> /tmp/i_am_data
```
2. we need to stop generating new external data files when using functions:
`override_onnx_input_shapes`
`override_onnx_batch_size`.
Not only it is wasteful and memory intensive for larger ONNX models (which will be soon ubiquitous in our SparseZoo), but also leads to accidental braking of the relationship between the …
=> [Fix] Add a patch that fixes the issue introduced by revamped `save_onnx` function

.github/ISSUE_TEMPLATE/bug_report.md, DEVELOPING.md, README.md, docs/user-guide/installation.md, examples/sparsestream/README.md, setup.py
Python 3.7 reaches it's EOL in ~2 weeks, this PR deprecates it's support
https://endoflife.date/python
=> Deprecate Py37

docker/Dockerfile
Updates misleading comment from dockerfile, this comment should have been updated when we moved to remove autoinstalls
=> Update misleading comment

docker/Dockerfile
Update dockerfile to remove autoinstall trigger (old pathway) since then the dockerfile has been updtaed to install from pypi
Update a typo where sparseml was being cloned instead of deepsparse
=> [BugFix] Update deepsparse dockerfile

src/deepsparse/image_classification/pipelines.py
Fix a bug where in image_classification pipelines, a model_dir with `model.onnx` was not being accepted properly
=> [Bugfix] `deepsparse.server` IC model_path

setup.py, src/deepsparse/version.py
this fixes a bug in the latest NM 1.5 supported transformers datasets that is incompatible with pandas 2.0.  Specifically, a removed kwarg is passed to pandas on `datasets.load_dataset`.
Future releases will support later datasets versions.
=> [1.5.1] restrict pandas to <2.0

setup.py
SUMMARY:
allows "wheel" generation on `macOS`. reuses the ENV, `NM_ALLOW_DARWIN`.
TEST:
checks after the updating the condition.
```
❯ export NM_ALLOW_DARWIN=0
❯ python3 setup.py sdist bdist_wheel
Loaded version 1.6.0 from /Users/andy/sidelot/wand/deepsparse/src/deepsparse/generated_version.py
File "/Users/andy/sidelot/wand/deepsparse/setup.py", line 223, in <module>
_check_supported_system()
File "/Users/andy/sidelot/wand/deepsparse/setup.py", line 188, in _check_supported_system
raise OSError(
OSError: Native Mac is currently unsupported for DeepSparse. Please run on a Linux system or within a Linux container on Mac. More info can be found in our docs here: https://docs.neuralmagic.com/deepsparse/source/hardware.html
```
and enabling it 
```
❯ export …
```
=> update setup.py to allow "wheel" construction on mac

.github/workflows/build-and-publish-tagged-images.yaml
rework if statement to target tags with `v` representing a release candidate
=> [BugFix] Update if statement to target tag starting with v

MANIFEST.in, setup.py
SUMMARY:
This enables packaging of the "dylib" files into `mac` "wheel" file. Updates `setup.py` to include files with extension `.dylib` and adds `src/deepsparse/neon` to the manifest via `recursive-include`.
TEST:
* verified the "wheel" package is built and installable.
* looked through "wheel" package contents and verified our magic bits are present.
```
steve_jobs@wontkins deepsparse % ls neon 
total 366928
drwxr-xr-x   5 steve_jobs  staff        160 Jun 26 15:20 .
drwxr-xr-x  29 steve_jobs  staff        928 Jun 26 15:20 ..
-rwxr-xr-x   1 steve_jobs  staff    1400372 Jun 26  2023 deepsparse_engine.so
-rwxr-xr-x   1 steve_jobs  staff    1195712 Jun 26  2023 libdeepsparse.dylib
-rwxr-xr-x   1 steve_jobs  staff  185267880 Jun 26  2023 libonnxruntime.1.12.0.dylib
```
* installed on …
=> include dylib in search for package contents

src/deepsparse/engine.py, src/deepsparse/pipeline.py, src/deepsparse/transformers/engines/nl_decoder_engine.py
A small adjustment that enables running the text generation pipeline with the deepsparse engine in the absence of `LIB.kv_cache` object.
Note:
- the inference confirms the correctness of the results (for the single-token engine to be precise, see notes below)
- because of the pending engine support for the operations that sit between the cache input and concat / concat and cache outputs, the data movement that happens on those branches is very time-consuming. This is why the initialization of the engines takes lot of time (up to 200s, see below)
- because the engine is unable to accept "empty" kv cache, multi-token engine defaults automatically to onnxruntime (this manifests itself through the warning: `Warning: Optimized runtime disabled - Detected dynamic input past_key_values.0.key dim …
=> [Text Generation] Run deepsparse engine without the LIB.kv_cache object

tests/conftest.py
`check_for_created_files()` is intended to insure large extraneous files(i.e from LLMs) aren't left in the root directory when running tests. This test case was failing due to `__pycache__` files and prometheus logs. These files are small so it should be fine that they are created. To fix the test I filtered out the `__pycache__` directories and `prometheus_logs.prom` files from the added files check, in addition to the GHA files that were already accounted for.
Run `make clean` then `make test`
```
E       AssertionError: 5 files created in current working directory during pytest run. Created files: 
{'/home/ubuntu/workspace/Github/TestDeepsparse/deepsparse/tests/deepsparse/pipelines/dynamic_import_modules/__pycache__/valid_dynamic_import.cpython-38.pyc', …
```
=> Fix Create Files Unit Test

src/deepsparse/utils/data.py
`join_engine_outputs` currently requires the outputs of `engine_forward` to be a list to comply with `Engine` forward calls, the `TextGeneration` pipeline breaks from this by returning tuples with for the join function is functionally the same.
=> allow Tuple type in join_engine_outputs

src/deepsparse/transformers/engines/nl_decoder_engine.py, src/deepsparse/transformers/pipelines/text_generation.py
The `NLDecoderEngine` can now infer the dtype of the kv cache input from the onnx graph. This is necessary in order to enforce the adequate dtype when creating an initial kv cache arrays.
The PR is complementary to https://github.com/neuralmagic/sparseml/pull/1648. Refer to that PR for manual tests description.
=> [Text Generation] Detect dtype of kv cache (float32/uint8) for text generation models

src/deepsparse/transformers/__init__.py
Needed to actually use the string `nm_transformers` rather than some variable
This was causing an error when hitting the warning:
```
File "deepsparse/transformers/__init__.py", line 47, in _check_transformers_install
f"installed via `pip install {nm_transformers}`"
NameError: name 'nm_transformers' is not defined. Did you mean: '_transformers'?
```
=> Update transformers/__init__.py warning

src/deepsparse/image_classification/pipelines.py, src/deepsparse/open_pif_paf/pipelines.py, src/deepsparse/utils/onnx.py
Some of our pipelines did not support using directories(with `model.onnx`) out of the box for deployment with server; Noting this used to work with certain tasks as a few pipelines did implement the logic to process  deployment directories.
Current PR propagates this support to all Pipelines; essentially it updates `model_to_path` function (used by all pipelines) to accept model directories as valid inputs; The test was performed using yolov5 model (as OD pipelines did not support model_directories initially)
Test:
model: 
```bash
$ sparsezoo.download "zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/pruned30-none-vnni" --save-dir ~/test-model
INFO:root:Downloading files from model 'zoo:cv/detection/yolov5-n/pytorch/ultralytics/coco/pruned30-none-vnni'
downloading...: …
```
=> [bug] Add out of the box support for deployment_directories

src/deepsparse/tasks.py
`text_generation` was missed as a valid task name for deepsparse `Pipeline`, this PR adds that
Test code:
```python
pipe = Pipeline.create(
model_path="zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
max_generated_tokens=128,
prompt_processing_sequence_length=1,
engine_type="deepsparse",
use_deepsparse_cache=False,
)
inference = pipe(sequences="def fib():")
print(inference)
)
```
Before: (ERROR)
```bash
raise ValueError(
ValueError: Unknown Pipeline task text_generation. Currently supported tasks are ['zero_shot_text_classification', 'glue', 'embedding_extraction', 'yolact', 'sentiment_analysis', 'yolov8', 'open_pif_paf', 'yolo', 'ner', 'question_answering', 'token_classification', …
```
=> [Bug] Add text_generation as a valid pipeline task

src/deepsparse/debug_analysis.py, src/deepsparse/engine.py, src/deepsparse/utils/onnx.py
Adds the ability to run kvcache via the debug_analysis.py.
=> Add kvcache support to debug_analysis.py and engine.py

src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/utils/timer.py
adds:
* bugfix for `TimerManager` workflow for `engine_forward` subtimings
* since `engine_forward` is always called in a child thread for batch splitting, it will not have access to the `current` timer contextvar
* see changes in `timer.py` `new_timer_context` for this
* adds `timer.time` helper contextmanager; see docstring for usage
* adds subtimings for prefill, generation and the individual autoregressive passes for each in the text generation pipeline
* see example in test plan for what these timings may look like
**test_plan:**
Manually for now - once we have more text gen pipeline tests, we can add assertions that the proper stages are generated in the timer manager:
```python
opt = Pipeline.create(task="opt", model_path=MODEL_PATH, …
```
=> [TextGeneration][Timer] text gen specific timings + improved timing tooling

src/deepsparse/transformers/engines/nl_decoder_engine.py, src/deepsparse/transformers/utils/helpers.py
The function `self.generate_token` expects to receive a single logits array of size `(vocab_size,)` and not `(batch_size, vocab_size)`.
=> [Text Generation][Fix] Update the logic from sampling from a distribution when `deterministic=False`

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/utils/data.py
This PR: https://github.com/neuralmagic/deepsparse/pull/1100 has moved `joint_engine_outputs` from the method of a `pipeline` to a separate helper function. This has broken the text generation pipeline, as it implements its own `self.joint_engine_outputs`. This PR fixes this issue, without implicitly falling back to the previous design.
=> [Fix] Bring back `join_engine_outputs` to be a `pipeline` method

setup.py, src/deepsparse/yolov8/pipelines.py, src/deepsparse/yolov8/utils/validation/deepsparse_validator.py, src/deepsparse/yolov8/utils/validation/detection_validator.py, src/deepsparse/yolov8/utils/validation/segmentation_validator.py, src/deepsparse/yolov8/validation.py
- Updated deepsparse support for yolov8
- Small similar changes to the ones made for sparseml's yolov8 update
- `process_engine_outputs` has a slight change. Previously providing `nm` for number of masks, which is no longer used by the yolov8 `non_max_suppression` function.
- Tested locally using both sparsezoo and yolov8 models for both segmentation and detection
- Workflows tested: pipeline creation and forward pass, annotation, eval and benchmarking 
1. detection: `"zoo:cv/detection/yolov8-m/pytorch/ultralytics/coco/base_quant-none"`
2. segmentation: `"zoo:cv/segmentation/yolov8-n/pytorch/ultralytics/coco/base-none"`
1. detection: `yolov8n.pt`
2. segmentation: `yolov8n-seg.pt`
Detection
```
model_path = "yolov8n.onnx" 
images = ["basilica.jpg"] …
```
=> [YOLOV8] Update version

src/deepsparse/base_pipeline.py
if num_cores is not an explicit kwarg of a bucketing pipeline it will trigger a key error on the changed line. this PR uses `.get` to default the value to `None` (this is the expected default of `Context`)
adds support for num_streams as well
**test_plan**
covered by pytest tests
=> [bugfix] qa tests - `KeyError: 'num_cores'`

src/deepsparse/utils/data.py, tests/deepsparse/pipelines/test_dynamic_batch_pipeline.py
flake8 was updated from 6.0 to 6.1, causing a new error when running `make quality`. I updated the offending lines to compare types with `is`/`is not` rather than `==`/`!=`
```
(.venv) sadkins@nmgpuserver3:~/deepsparse$ make quality
Running copyright checks
python3 utils/copyright.py quality 'examples/**/*.py' 'scripts/**/*.py' 'src/**/*.py' 'tests/**/*.py' 'utils/**/*.py' setup.py 'docs/**/*.md' 'docs/**/*.rst' 'examples/**/*.md' 'scripts/**/*.md' CODE_OF_CONDUCT.md CONTRIBUTING.md DEVELOPING.md README.md
314 files have copyrights
Running python quality checks
black --check examples tests src utils setup.py;
All done! ✨ 🍰 ✨
249 files would be left unchanged.
isort --check-only examples tests src utils setup.py;
Skipped 6 files
flake8 examples tests src utils setup.py; …
```
=> Fix Flake 6.1 Quality Errors

src/deepsparse/transformers/pipelines/text_generation.py
Dynamically determine which inputs are actually needed by the model.
=> [Text Generation][MPT] Filter out the appropriate `engine_inputs` for `autoregressive_inference`

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/text_generation.py, tests/deepsparse/pipelines/test_pipeline.py
Allows usage of the [Transformers TextStreamer and TextIteratorStreamer classes](https://huggingface.co/docs/transformers/internal/generation_utils#transformers.TextStreamer) with DeepSparse
```python
from transformers import TextStreamer
pipe = Pipeline.create(
task="codegen",
model_path="zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
max_generated_tokens=64,
prompt_processing_sequence_length=1,
use_deepsparse_cache=False,
)
streamer = TextStreamer(pipe.tokenizer)
_ = pipe(sequences="def fib():", streamer=streamer)
```
https://github.com/neuralmagic/deepsparse/assets/3195154/ef17fd95-a54f-4709-98df-1ce6412a2911
===
This also extends beyond printing to stdout by using TextIteratorStreamer
```python
from …
```
=> Implement `streamer` for text-generation and add `context` arg to `Pipeline.engine_forward`

src/deepsparse/transformers/pipelines/pipeline.py
Give a user an option to enable running remote code through pipeline argument e.g.
```
Pipeline.create(task="...", trust_remote_code = True)
```
By default `trust_remote_code=False`.
=> [Transformers] Add an argument `trust_remote_code` on transformers pipeline initialization.

src/deepsparse/transformers/pipelines/embedding_extraction.py, src/deepsparse/transformers/pipelines/question_answering.py, src/deepsparse/transformers/pipelines/text_classification.py, src/deepsparse/transformers/pipelines/token_classification.py, src/deepsparse/transformers/pipelines/zero_shot_text_classification.py
Fix bug for  https://neuralmagic.slack.com/archives/C0592FX3215/p1687210067995879
Example:
```python3
path = "path"
task = "text-classification",
model_path = path,
batch_size=8,
num_cores=None,
sequence_length = [2, 128],
)
text = "We are flying from Texas to California"
pipeline(text)
```
Before:
```bash
(.venv) ubuntu@quad-mle-2:~/george/nm/deepsparse$ python3 scratch/_p.py 
...
2023-08-04 01:19:39 __main__     INFO     Overwriting in-place the input shapes of the transformer model at /home/ubuntu/.cache/sparsezoo/bert-large-squad_wikipedia_bookcorpus-pruned80.4block_quantized/bert-large-squad_wikipedia_bookcorpus-pruned80.4block_quantized/model.onnx
Token indices sequence length is longer than the specified maximum sequence …
```
=> use max sequence length for tokenization

src/deepsparse/utils/onnx.py
It was unnecessary to load in weights to look at the outputs
=> Don't load external data for `default_cached_outputs`

src/deepsparse/engine.py, src/deepsparse/tasks.py, src/deepsparse/transformers/pipelines/text_generation.py
Includes the following fixes:
* adds support for internal KV cache in multi model engine (multi stream)
* adds text generation to complete list of supported tasks (CLI)
* removes numpy.ndarray from output schema (FastAPI requirement)
**test_plan:**
verify the following command (previously failing) now works:
```bash
deepsparse.server --task text-generation --config_file config.yaml
```
where `config.yaml` includes:
```yaml
{
  "name": "opt_model_server_config",
  "num_cores": 2,
  "num_workers": 2,
  "endpoints": [
      {
          "task": "text_generation",
          "model": "zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
          "route": "/predict",
      },
  ],
}
```
=> [TextGeneration] fixes to support text gen pipeline in server

.github/workflows/publish-nightly-docker.yaml
This PR adds support to build and push deepsparse-nightly docker images to github container registry
The workflow will be run once everyday at 1:00 am, and includes the following images:
- deepsparse-nightly  Latest deepsparse-nightly from main, will all dependencies installed
- deepsparse-nightly:latest Same as above
- deepsparse-nightly:YYYYMMDD deepsparse-nightly from YYYYMMDD with all dependencies installed
- deepsparse-nightly:base-YYYYMMDD deepsparse-nightly from YYYYMMDD with only base dependencies installed
These images will live under the https://github.com/orgs/neuralmagic/packages?repo_name=deepsparse
and can be pulled using:
```bash
docker pull <IMAGE-NAME>
```
Equivalent in purpose to Sparseml Diff: https://github.com/neuralmagic/sparseml/pull/1684
=> Nightly Docker Images

src/deepsparse/transformers/metrics.py
...so it reflects the actual attribute name of class `TextGenerationPipeline`: `self.cache_support_enabled`
=> [Perplexity Evaluation] [Fix] Update the attribute name

src/deepsparse/server/cli.py, src/deepsparse/tasks.py
request from product - allows whitespaces to be ignored when matching task names. specifically allows `text generation` to be a valid task name
**test_plan:**
previously failing command now works:
```
deepsparse.server --task "text generation"
```
=> allow spaces in task names to match

src/deepsparse/transformers/metrics.py
A dependency issue where `torch` isn't installed with `deepsparse[transformers]`
```bash
#!/usr/bin/env bash
set -euf -o pipefail
rm -rf venv
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -e "./[transformers]"
deepsparse.transformers.eval_downstream --help
```
Before This PR, above script fails with the following error:
```bash
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
File "/home/rahul/projects/deepsparse/venv/bin/deepsparse.transformers.eval_downstream", line 5, in <module>
from deepsparse.transformers.eval_downstream import main
File "/home/rahul/projects/deepsparse/src/deepsparse/transformers/eval_d …
```
=> [BugFix] Delay torch import until needed for `deepsparse.transformers.eval_downstream`

src/deepsparse/transformers/eval_downstream.py, src/deepsparse/transformers/pipelines/text_generation.py
When we try to create a multi-token deepsparse engine where `prompt_processing_length == sequence_length`, this engine will default to onnxruntime:
```bash
[nm_ort 7f9cd3579740 >WARN<  is_supported_graph src/onnxruntime_neuralmagic/supported/ops.cc:144] Warning: Optimized runtime disabled - Detected dynamic input past_key_values.0.key dim 2. Set inputs to static shapes to enable optimal performance.
```
this is a known issue reported by the runtime team. The crux is: if `prompt_processing_length == sequence_length`, the initial kv cache tensors will be empty, and this is prohibitive in the engine - we cannot have empty kv cache values in there.
=> [Text Generation] [Fix] Raise error when we use deepsparse engine and `prompt_processing_length == sequence_lenght`

src/deepsparse/server/helpers.py, src/deepsparse/server/server.py
**Asana Ticket:** https://app.asana.com/0/1205229323407165/1205248270105783/f 
When a TextGeneration pipeline is run through DeepSparse Server with `return_logits=true`, the request fails because the logits are returned as `numpy.ndarray` which is not JSON serializable. To fix this, I added a helper function that converts numpy arrays to lists before returning them to the client
Launch a server:
`deepsparse.server --config_file server_error_config.yaml`
server_error_config.yaml:
```
{
"name": "opt_model_server_config",
"endpoints": [
{
"task": "text_generation",
"model": "zoo:nlg/text_generation/codegen_multi-350m/pytorch/huggingface/bigquery_thepile/base-none",
"route": "/gen",
}
]
}
```
Send request from python, it should now be processed correctly
```
>>> r = …
```
=> Bug Fix: Make Numpy Array Outputs JSON Serializable for Server

src/deepsparse/transformers/utils/decoder_kv_cache.py
As reported by @mgoin and investigated by myself, the `update` method in the KVCacheDecoder is very slow.
Profiling has shown that this is due to the repeated use of the `numpy.delete` function:
This discussion:
https://stackoverflow.com/questions/30399534/shift-elements-in-a-numpy-array
hints that the most elegant and quite efficient replacement for `numpy.delete` would be slicing the arrays. This is the change that this PR introduces.
Short benchmarking numbers:
=> [Text Generation] Optimize the slow `update` method in the KVCacheDecoder

src/deepsparse/transformers/pipelines/text_generation.py
This PR fixes the following issues with text-generation Pipelines:
Test code for 1:
```python
ZOO_STUB = "zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none"
PIPELINE_INPUT = {
"sequences": "Write a function in Python to find the factorial of a given number."
}
TASK = "text_generation"
_MAX_TOKENS = 512
if __name__ == "__main__":
pipeline_args = {
"task": TASK,
"model_path": ZOO_STUB,
"max_generated_tokens": _MAX_TOKENS,
"force_max_tokens": True,
}
pipeline = Pipeline.create(**pipeline_args)
result = pipeline(**PIPELINE_INPUT)
token_count = len(pipeline.tokenizer.tokenize(result.sequences[0]))
assert token_count == _MAX_TOKENS, f"want: {_MAX_TOKENS}, got: {token_count}"
print(f"SUCCESS! got {token_count} …
```
=> [BugFix]: `force_max_tokens` not respected by text-gen pipelines

src/deepsparse/transformers/pipelines/text_generation.py
Our pipelines right now generate one extra token per inference than hugging face pipelines, this PR fixes that.
Additionally this also matches the generated logits with generated tokens.
=> Conform output of TextGenerationPipelines with HuggingfacePipelines

setup.py, src/deepsparse/clip/README.md
- Update clip instructions and dependencies while making sure clip works end-to-end (sparseml export, deepsparse pipeline inference)
=> [CLIP] Update clip dependencies, README.md

src/deepsparse/transformers/pipelines/text_generation.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
This PR adds a callback attribute to TextGenerationInput
`callback` is a callable that will be invoked on each generated token, and returns a boolean value.
If callback returns false, further generation of tokens is stopped
Test Code:
```python
start = 0
def dummy_callback(token):
global start
start += 1
return start < 3
if __name__ == "__main__":
codegen_pipeline = Pipeline.create(
model_path = "zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none"
)
inputs = {
"sequences": ["def fib(a, b, accumulator=0)"]*3,
"callback": dummy_callback,
"return_logits": True,
}
outputs = codegen_pipeline(**inputs)
assert ( shape:=outputs.logits.shape[1]) == 3, f"Expected 3 tokens, got {shape}"
```
Also …
=> [Feature] Add callback for Text Generation Pipelines

src/deepsparse/transformers/pipelines/text_generation.py
This PR adds a stop argument to TextGenerationInputSchema
Argument description:
```
A string or a list of strings that will be used as stop tokens. (token generation will stop when any of the stop tokens is generated). Set to `None` to ignore this parameter. Default is `None`."
```
Local Test:
```python
codegen_pipeline = Pipeline.create(
model_path = "zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none"
)
inputs = {
"sequences": "def fib(a, b, accumulator=0)",
"stop": ["def", "int"],
}
outputs = codegen_pipeline(**inputs)
print(outputs.sequences)
```
Output:
```bash
)
2023-08-25 15:12:00 deepsparse.transformers.utils.helpers INFO     Overwriting in-place the input shapes of the …
```
=> Add stop argument to TextGenerationInput

src/deepsparse/transformers/metrics.py
Before: perplexity was broken
Now:
```bash
zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none -d openai_humaneval
openai_humaneval eval results: {'mean_perplexity': 4.852397926896811, 'perplexities': [2.4682281017303467, 5.375603199005127, 11.334624290466309, ...
```
=> [Fix][Eval Downstream] Include prompt logits in the perplexity calculation

src/deepsparse/benchmark/benchmark_model.py, src/deepsparse/debug_analysis.py
Take the implementation for benchmark in https://github.com/neuralmagic/deepsparse/pull/1142 and apply to debug_analysis. Also update help usage and change default seq_len to 512
=> Automatically analyze in auto-regressive setting

src/deepsparse/transformers/pipelines/text_generation.py
A simple improvement that streamlines the pipeline.
If `prompt_processing_sequence_length == 1`, we are essentially running single-token prompt prefill , so we should not be initializing and running the additional engine.
=> [Text Generation][Enhancement] If `prompt_processing_sequence_length` == 1, do not inititalize multitoken_engine

examples/openai-server/README.md, examples/openai-server/client.py, examples/openai-server/server.py, examples/openai-server/test.py
Thanks to @dsikka for noticing the current outputs of the server were garbage - the pipeline was returning only the tokens delta during streaming rather than the ongoing concatenated text.
Also implement full support for non-streaming.
Start the server with:
```
python examples/openai-server/server.py --model zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none
```
And hit it with a prompt request:
```
curl http://localhost:8000/v1/completions \                                                                                                                                  
-H "Content-Type: application/json" \
-d '{
"model": "zoo:nlg/text_generation/codegen_mono-350m/pytorch/huggingface/bigpython_bigquery_thepile/base-none",
"prompt": "def …
```
=> Fixes for openai server example

setup.py
this is for compatibility with the maximum currently allowed version of `starlette`. `anyio` just pushed a 4.0.0 that is incompatible with earlier versions of `starlette`. 
Note that this is now fixed in later versions (`deepsparse` has not yet tested against newer versions of `fastapi` and `starlette`). See: https://github.com/encode/starlette/pull/1936
from internal bug report:
```
Our Deepsparse GHA is failing with starlette error: AttributeError: module 'anyio' has no attribute 'start_blocking_portal'
```
=> [server] pin anyio support to <4.0.0

src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/transformers/utils/helpers.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
For this ticket: 
https://app.asana.com/0/1201735099598270/1205276886236972/f
- Refactors the TextGeneration Constructor to remove the `max_tokens` argument and makes it part of the pipeline input
- Adds `num_generated_predictions` to the input as well, which dictates the number of sequences that are generated for a given input. Similar to the hugging face implementation, we repeat the input based on the number provided, defaulting to 1. When `num_generated_predictions` is > 1,  the engine's `deterministic` property is togged to False
- In the case where the value is > 1, the output is a list of lists, where each list includes the generated sequences for a given prompt. This updates the sequences output to be one of `str, List[str], and List[List[str]]`
- Tested locally using the new …
=> [TextGeneration] max token refactor

src/deepsparse/transformers/pipelines/pipeline.py
This PR is motivated to remove the dependency on the "trust-remote-code" argument for deepsparse transformers pipelines.
In addition to an additional flag, this argument also meant that custom scripts needed for the PyTorch definition of models needed to be carried over in the deployment folder, even though the PyTorch definition is not needed for deepsparse inference.
The dependency was introduced by using the AutoConfig class to load the model config. This PR replaces this with PretrainedConfig instead. AutoConfig is a class that wraps PretrainedConfig and does additional checks to guarantee that the loaded config matches what the model definition uses. By doing this replacement these checks are skipped and the model definitions is not needed any longer.
The model config at this moment …
=> Remove dependency on trust-remote-code

src/deepsparse/transformers/helpers.py, src/deepsparse/transformers/pipelines/pipeline.py
#1232  introduced the new pathway for instantiating transformer configs. The new pathway emits a warning stdout that gets printed on every instantiation of the pipeline. 
```bash
f"You are using a model of type {config_dict['model_type']} to instantiate a model of type "
f"{cls.model_type}. This is not supported for all configurations of models and can yield errors."
```
This print is not only potentially confusing for the user, but also breaks our tests (as some tests explicitly look for a string "error" in the stdout).
This PR introduces a lightweight context manager, that enables temporary reduction/increase of the config level for the particular module logger.
=> [Fix] Temporary suppress transformers logging

src/deepsparse/transformers/pipelines/text_generation.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
- Add `GeneratedText` schema to the `TextGeneration` pipeline
- Update the `TextGenerationOutput` to use the `GeneratedText` class for each output sequence
- Use the `FinishReason` enum for the logged reason for generation to complete. Question - missing reason for any generic callback?
- Following internal docs: https://github.com/neuralmagic/internal-docs/blob/0bd3bf122c1f8c5871b085916d04cb0266a0a332/requirements/deepsparse/natural-language-generation/main.md
- One missing piece in in the `GeneratedText` is the use of alias
- Also, we're keeping the `prompt` in the `TextGenerationOutput` as opposed to the corresponding `GeneratedText` which seems counterintuitive?
- Tested locally - sample output:
``` …
```
=> [TextGeneration] Add `GeneratedText` and update `TextGenerationOutput`

src/deepsparse/debug_analysis.py
Allow support for exporting CSVs from debug analysis making analysis easier. 
Example output:
https://docs.google.com/spreadsheets/d/1EsxRffS2p-1lrsVz35EDI02qBnNK1RcUbHN0uGkhLbE
=> Add CSV export to `debug_analysis`

src/deepsparse/transformers/helpers.py, src/deepsparse/utils/onnx.py
Adds the capability to download models straight from HF repos if the stub is prepended with `hf:`.
If you want to use this model https://huggingface.co/mgoin/TinyStories-1M-deepsparse, then passing in `model_path="hf:mgoin/TinyStories-1M-deepsparse"` will suffice
```python
import deepsparse
pipe = deepsparse.Pipeline.create(task="text-generation", model_path="hf:mgoin/TinyStories-1M-deepsparse")
pipe(sequences="hello")
```
Output:
```
>>> import deepsparse
>>> pipe = deepsparse.Pipeline.create(task="text-generation", model_path="hf:mgoin/TinyStories-1M-deepsparse")
2023-09-20 14:10:19 deepsparse.transformers WARNING  The neuralmagic fork of transformers may not be installed. It can be installed via `pip install nm_transformers`
2023-09-20 14:10:20.061685: W …
```
=> Support loading HF repos with `hf:` stubs

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/text_generation.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
- Enable the ability to stream the generated tokens as they're produced, as opposed to waiting for the completed generated sequence at the end. 
- Adds `streaming` as a boolean flag as an input which then toggles the class `streaming` flag
- Each generated token when streaming is enabled, is its own instance of `GeneratedText` which also includes whether or not the stream is complete with the `finish` flag
- Note: this makes the output from this pipeline a generator as well
Locally Testing the following pipeline runs, with and without streaming:
Without streaming:
```python
model_path="/home/dsikka/.cache/sparsezoo/neuralmagic/opt-1.3b-opt_pretrain-quantW8A8/deployment",
engine_type="onnxruntime"
) …
```
=> [TextGeneration] Add Streaming Functionality

tests/utils/engine_mocking.py
latest version of ORT has a hard requirement for providers to be set. this PR updates any inference session that does not have it set 
**test_plan:**
QA Team + GHA
=> explicitly set ORT providers on all InferenceSession creations

tests/deepsparse/pipelines/test_pipeline.py
It is perfectly reasonable for the two threads to only be 1.6x faster than one thread
=> Raise limit of `test_pipeline_call_is_async` further

src/deepsparse/benchmark/stream_benchmark.py, src/deepsparse/pipeline.py, src/deepsparse/transformers/metrics.py, src/deepsparse/transformers/pipelines/text_generation.py
This is a minimal PR adds minor updates to our code.
1) Updates usage of idiom `max([for .. clause ..])` -> `max(for .. clause)`, similar update for `min([..])`
2) In one of my comments on a previous PR I suggested a two line change on one line, which was merged in and lead to working but not so great if condition this PR also updates that
This is the original comment: https://github.com/neuralmagic/deepsparse/pull/1246#discussion_r1333454411
=> Add minor updates

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/transformers/utils/helpers.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
- Update the input to the pipeline to support a `transformers.GenerationConfig`. This will essentially be used in replacement of many of the inputs that we provide as separate fields (such as `num_return_sequences`, `top_k`, etc).
- Supports path to a json with the config file, dictionary, or `transformers.GenerationConfig` object
- The user can provide the config either on the pipeline level or the input level. If an input level config is provided, it will override the pipeline level config and be used for generation. Otherwise, the one provided during pipeline creation will be used. If neither are given, defaults set in the `GenerationDefaults` class will be used
- If the user provides a generation config, either on the pipeline level or on the input level but not all the values are …
=> [TextGeneration] Update pipeline inputs to support GenerationConfig

src/deepsparse/transformers/utils/helpers.py, tests/deepsparse/transformers/utils/test_helpers.py
This is a temporary change to be reverted - right now there are reported segfaults when running internal kv cache with empty placeholder arrays for ONNX graph input
**test_plan:**
@tlrmchlsmth to verify
**revert_plan:**
@tlrmchlsmth to confirm when revert is safe
=> [Temporary Patch] ignore `empty` do not pass empty kv cache to runtime

src/deepsparse/transformers/pipelines/text_generation.py
from internal specs:
```python
text_pipeline = TextGeneration(model=MODEL, **kwargs)
text_result = text_pipeline(prompt=PROMPT, **kwargs)
```
**test_plan:**
local
```python
"text-generation",
model_path="/home/benjamin/neuralmagic/models/codegen_mono-350m-bigpython_bigquery_thepile-pruned50/deployment",
engine_type="onnxruntime"
)
pipeline(prompt="def hello_world():", generation_config=dict(max_new_tokens=10))
```
=> [Text Gen UX] Add `prompt` as input param alias

src/deepsparse/transformers/pipelines/text_generation.py
request from product (@mgoin)
support for `pipe("text")` instead of requiring `pipe(sequences="text")`
**test example:**
```python
"text-generation",
model_path="/home/benjamin/neuralmagic/models/codegen_mono-350m-bigpython_bigquery_thepile-pruned50/deployment",
engine_type="onnxruntime"
)
pipeline("def hello_world:", generation_config=dict(max_new_tokens=10))
```
=> [Text Gen UX] default pipeline input to  value

src/deepsparse/transformers/pipelines/text_generation.py
In one of our recent changes to `TextGenerationPipeline`,  a function within a function was moved outside, but the original function wasn't deleted. This lead to a duplicate "dead" function not used anywhere.
This PR removes that dead function `_create_generated_text_output`
Note: there is already a `_create_generated_text_output` function defined at the class level
=> Remove Dead Code

src/deepsparse/version.py, tests/utils/engine_mocking.py
This is a cherry pick of #1262 for release/1.5, additionally updates the patch version
=> [Cherry pick] #1262 explicitly set ORT providers on all InferenceSessions

src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/transformers/utils/helpers.py
Update the `text_generation` pipeline to support kwargs for generation_config attributes. 
1. kwargs only
```python
model_path="/home/dsikka/.cache/sparsezoo/neuralmagic/opt-1.3b-opt_pretrain-quantW8A8/deployment",
engine_type="onnxruntime",
)
inference = pipeline(prompt=["how are you?"], num_return_sequences=2, do_sample=False, max_length=10)
print(inference)
```
2. Combination of GenerationConfig input and kwargs
```python
model_path="/home/dsikka/.cache/sparsezoo/neuralmagic/opt-1.3b-opt_pretrain-quantW8A8/deployment",
engine_type="onnxruntime",
)
generation_config = {"do_sample": True}
inference = pipeline(prompt=["how are you?"], generation_config=generation_config, …
```
=> [TextGeneration] Add kwarg support for generation config attributes

src/deepsparse/transformers/README.md
This PR fixes two headers in the transformers README.md file:
1. The top-of-file header (recently broken in #1279)
2. The “Token Classification” header (was incorrectly a fourth-level, fixed to be third-level)
=> Fix headers in transformers/README.md

src/deepsparse/transformers/pipelines/text_generation.py
Summary:
This fixes the issue where if the user has set max_length=1, finish reason is never populated as we never go through the loop in engine_forward. max_length=1 is needed for our perplexity calculation so this PR will unblock that from being completed.
Testing:
Tested locally
=> [TextGeneration] Fix max_length = 1, repeat token

src/deepsparse/transformers/pipelines/chat.py, src/deepsparse/transformers/pipelines/text_generation.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
This PR fixes a bug with `ChatPipeline` where streaming code would throw a `TypeError`, now the execution is as expected
Reproduction Code:
```python
import inspect
streaming = True
input_text = "def fib("
chat_pipeline = Pipeline.create(
task="chat",
model_path="/home/rahul/.cache/sparsezoo/neuralmagic/codegen_mono-350m-bigpython_bigquery_thepile-base/deployment",
)
predictions = chat_pipeline(**{"sequences": [input_text]}, streaming=streaming)
assert inspect.isgenerator(predictions), "Predictions should be a generator"
for i, prediction in enumerate(predictions):
print(f"Prediction {i}: {prediction}")
```
Output: 
Before this PR:
```bash
File
"/home/rahul/projects/deepsparse/src/deepsparse/pipeline.py", line 284, in __call__
pipeline_outputs = …
```
=> [BugFix] Error with streaming in Chat Pipeline

setup.py, src/deepsparse/cpu.py
SUMMARY:
* removes NM_ALLOW_DARWIN ENV. this means `deepsparse` will function on "Darwin" without needing to set the "secret" ENV.
TEST PLAN:
testing locally and in automation
=> remove NM_ALLOW_DARWIN

src/deepsparse/transformers/pipelines/text_generation.py
- Fix this bug: https://app.asana.com/0/1205229323407165/1205618236158808/f
```
from pathlib import Path
from huggingface_hub import snapshot_download
MODEL_PATH = snapshot_download(repo_id="mgoin/TinyStories-33M-quant-deepsparse")
model_path=MODEL_PATH,
engine_type="onnxruntime",
)
inference = pipeline(prompt="She is in", streaming=True, max_length=17)
for i in inference:
print(i)
```
```
created=datetime.datetime(2023, 10, 3, 10, 40, 13, 480701) prompts='She is in' generations=[GeneratedText(text=' the', score=None, finished=False, finished_reason=None)]
created=datetime.datetime(2023, 10, 3, 10, 40, 13, 490254) prompts='She is in' generations=[GeneratedText(text=' kitchen', score=None, finished=False, …
```
=> [TexgGeneration][Bug] streaming skips generated token added from last prompt token

src/deepsparse/transformers/utils/helpers.py, tests/deepsparse/transformers/utils/test_helpers.py
We've resolved the segfault that was occurring in sparse quantized MPT prefill so we can reenable external input deallocation.
=> Revert #1263

src/deepsparse/transformers/engines/nl_decoder_engine.py, src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/utils/timer.py
For this ticket: https://app.asana.com/0/1205229323407165/1205618233879512/f
Tested locally with gradio/non-gradio examples
=> [TextGeneration][Bug] Fix timer

src/deepsparse/utils/onnx.py
fixes issue in #1247 where only `model.onnx` would be downloaded by default in `model_to_path` from a deployment directory. this breaks flows such as `benchmark` and `compile_model` which rely on only the `model_to_path` for the onnx file path from zoo.  with this change the function now also searches for and downloads `.data*` files
**test_plan:**
verified locally that data file downloads now trigger with a stub such as `zoo:mpt-7b-dolly_mpt_pretrain-base` where they weren't before
=> [bugfix] model_to_path should also download .data files from zoo

setup.py, src/deepsparse/server/cli.py, src/deepsparse/server/deepsparse_server.py, src/deepsparse/server/openai_server.py, src/deepsparse/server/sagemaker.py, src/deepsparse/server/server.py
- This PR is focused on updating the openai integration such that it is more independent of the deepsparse server, leveraging the server refactor
- This PR allows multiple text generation models to hosted using the single `/v1/chat/completions` endpoint, adds the `/v1/models` endpoint, updates the base routes, and also adds a separate openai specific workflow command
- On the command line, the following command can be used:
```
deepsparse.openai sample_config.yaml 
```
Here, `sample_config.yaml` has the following structure:
```
num_cores: 2
num_workers: 2
endpoints:
model: zoo:nlg/text_generation/opt-1.3b/pytorch/huggingface/opt_pretrain/pruned50_quantW8A8-none
```
- This launches a FASTAPI app with the following endpoints:
```python
import openai
openai.api_key = …
```
=> [server] Update OpenAI Model Support

src/deepsparse/transformers/helpers.py
recent changes simplify downloading transformers deployment files by just running `zoo_model.depoyment.path` while this works in the base case, @dbarbuzzi found that if some files are already downloaded (ie just onnx files for benchmarking) the additional configs will not be downloaded by this command.
this pr simply loops over the deployment directory's contents to makes sure that all files get downloaded before any pipelines run
**test_plan:**
manually verified
=> [bugfix] enforce that all transformer deployement files are downloaded by pipeline

utils/artifacts.py
Tested using `pip install -e .` on AWS m7g.2xlarge and M1 Macbook with python 3.10
=> Add support for pulling down ARM and MacOS artifacts

src/deepsparse/server/sagemaker.py, src/deepsparse/server/server.py, tests/server/test_endpoints.py
Summary
- Small update such that kwargs for generation can be given as an input to the server, without having to just be defined through the `generation_config` arguments
- Small test updates + typo fix in sagemaker
Testing:
sample config:
```yaml
num_cores: 2
num_workers: 2
endpoints:
- task: question_answering
model: zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/12layer_pruned80_quant-none-vnni
model: zoo:opt-1.3b-opt_pretrain-quantW8A8
kwargs: {"generation_config": {"max_length": 100}}
```
We can start a server with the generation config and also send requests with attributes outside of the config:
```python
import requests
url = "http://localhost:5543/v2/models/text_generation-0/infer"
obj = {"prompt": "Hey! How are you?", "max_length": 10} …
```
=> [server] Fix tests + allow server to parse generation kwargs

src/deepsparse/transformers/helpers.py, src/deepsparse/utils/onnx.py
to land with https://github.com/neuralmagic/sparsezoo/pull/373
updates deployment directory downloads to target the compressed directory instead of loose files
**simple test:**
```python
"text-generation",
model_path="zoo:nlg/text_generation/mpt-7b/pytorch/huggingface/mpt_chat/base-none",
engine_type="onnxruntime"
)
pipeline("test", generation_config=dict(max_new_tokens=10))
```
=> download compressed deployment directory

src/deepsparse/transformers/helpers.py
Reverting my change from #1324 
Back then, I was not aware that this property of the sparsezoo `Model` was an intended change (assumed it was a typo)
=> [Fix] Bring back `model.deployment_directory_path`

src/deepsparse/transformers/helpers.py, src/deepsparse/utils/onnx.py
All of the noisy logs seems like a bad user experience so I think we should move them to the debug level:
```
2023-10-25 17:05:12 deepsparse.utils.onnx INFO     Overwriting in-place the input shapes of the transformer model at /root/.cache/huggingface/hub/models--mgoin--TinyStories-33M-quant-ds/snapshots/6d30653d6fd728a5b8121a2e6801408c79c3c179/model.onnx
INFO:deepsparse.utils.onnx:Overwriting in-place the input shapes of the transformer model at /root/.cache/huggingface/hub/models--mgoin--TinyStories-33M-quant-ds/snapshots/6d30653d6fd728a5b8121a2e6801408c79c3c179/model.onnx
```
=> Move inplace shape override log to debug

src/deepsparse/transformers/utils/token_generator.py, tests/deepsparse/transformers/utils/test_token_generator.py
fixes two issues with `top_p`:
1. setting filtered values to `-inf` is incompatible with `numpy.choice`, was causing issues with numpy.choice in certain scenarios
2. fixes top_p application to grab the true top `p` percent by weight of the logits softmax distribution (previously was sorting  descending causing the least likely tokens would have the highest density)
**minimal reproducible example:**
```python
"text-generation",
model_path="hf:neuralmagic/mpt-7b-chat-pruned50-quant",
engine_type="onnxruntime",
sequence_length=32,
prompt_sequence_length=1,
)
generation_config = dict(top_p=0.5, max_new_tokens=5, do_sample=True)
pipeline("def hello_world:", generation_config=generation_config)
```
**test_plan:**
@horheynm to add unit …
=> [text generation] fix issues with top_p

setup.py, src/deepsparse/sentence_transformers/README.md, src/deepsparse/sentence_transformers/__init__.py, src/deepsparse/sentence_transformers/benchmark_encoding.py, src/deepsparse/sentence_transformers/sentence_transformer.py
Tighten up performance for DeepSparseSentenceTransformer by implementing bucketing alongside a dynamic model for small sequence lengths and batching. This also comes with a benchmarking script that shows speedup compared against SentenceTransformers
```bash
python benchmark_encoding.py --base_model BAAI/bge-small-en-v1.5 --sparse_model zeroshot/bge-small-en-v1.5-quant
[Standard SentenceTransformer] Encoded 100 sentences of length 700 in 10.42 seconds.
[DeepSparse] Encoded 100 sentences of length 700 in 4.04 seconds.
[DeepSparse Optimized] Encoded 100 sentences of length 700 in 1.82 seconds.
```
=> Add bucketing to DeepSparseSentenceTransformer

setup.py
Asana ticket: [NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported. (from datasets)](https://app.asana.com/0/1203126676641557/1205796604651399/f)
The latest fsspec release(2023.10.0) caused a breaking change with the datasets library. Upgrading our datasets version fixes the issue. Alternatively, we can downgrade fsspec. This change was already pushed to SparseML main
=> update datasets version

src/deepsparse/server/helpers.py, tests/server/test_helpers.py
Currently, the `prep_outputs_for_serialization` function assumes that `pipeline_outputs` cannot be arbitrarily nested (allows up to one level of nesting). This is why, for more complex `BaseModels` returned by the python (e.g. `TextGenerationOutput`), the function will not properly convert nested numpy arrays to lists for serialization.
My diff makes sure that any `pipeline_output: BaseModel` that contains an arbitrary number and nesting depth of any fields that are either a `BaseModel`, `list` of `numpy.ndarray` is supported.
As a result, we can now serialize logits of the LLM output, that previously was not properly converted from numpy array to a list. 
```python
import requests
model_path = "hf:mgoin/TinyStories-1M-deepsparse"
prompt =  ["name one former president of the USA"] …
```
=> Enable preparing nested OutputSchemas for serialization

src/deepsparse/transformers/helpers.py, src/deepsparse/utils/onnx.py
Tada - just like the transformer pipeline, support HF paths in common places like Engine construction and benchmarking
```
deepsparse.benchmark hf:mgoin/TinyStories-33M-ds -q
Fetching 9 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 139294.23it/s]
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.6.0 COMMUNITY | (3d596172) (optimized) (system=avx512_vnni, binary=avx512)
Original Model Path: hf:mgoin/TinyStories-33M-ds
Batch Size: 1
Scenario: sync
Throughput (items/sec): 346.2459
Latency Mean (ms/batch): 2.8814
Latency Median (ms/batch): 2.8814
Latency Std (ms/batch): 0.2968
Iterations: 3463
```
=> Add hf: stub support to model_to_path

src/deepsparse/v2/operators/engine_operator.py, src/deepsparse/v2/operators/operator.py, src/deepsparse/v2/pipeline.py, src/deepsparse/v2/routers/router.py, src/deepsparse/v2/schedulers/scheduler.py, src/deepsparse/v2/schedulers/scheduler_group.py, src/deepsparse/v2/text_generation/__init__.py, src/deepsparse/v2/text_generation/join_output.py, src/deepsparse/v2/text_generation/pipeline.py, src/deepsparse/v2/text_generation/prep_for_prefill.py, src/deepsparse/v2/text_generation/process_inputs.py, src/deepsparse/v2/text_generation/process_outputs.py
Summary
- Introduce functionality such that multiple prompts can run, using `SPLIT_ROUTE` and `JOIN_ROUTE` nodes.
- Allows us to enable the `num_return_sequences` generation attribute, such that multiple generations can be produced
- Potentially still needs a good testing strategy? 
Testing
```python
model_path = "hf:mgoin/TinyStories-1M-deepsparse"
pipeline = TextGenerationPipeline(
model_path, prompt_sequence_length=3
)
def run_requests():
prompts = ["The dog barked", "Hello!"]
outputs = []
input_value = TextGenerationInput(prompt=prompts, generation_kwargs={"num_return_sequences": 2, "do_sample": True, "max_length": 20})
output = pipeline(input_value)
return output
output = run_requests()
for x in output.generations:
print("\n")
print(x)
```
Outputs:
```bash
[GeneratedText(text=' and …
```
=> [Pipeline Refactor] Split/Join Functionality for multiple prompts

src/deepsparse/transformers/engines/nl_decoder_engine.py
https://github.com/neuralmagic/deepsparse/pull/1337 into `release/1.6`
=> [Cherry Pick] [Fix] Remove erronous LIB.kv_cache input when using external kv cache management 

src/deepsparse/v2/schedulers/utils/__init__.py, src/deepsparse/v2/schedulers/utils/continuous_batching_queues.py, tests/deepsparse/v2/schedulers/__init__.py, tests/deepsparse/v2/schedulers/utils/__init__.py, tests/deepsparse/v2/schedulers/utils/test_continuous_batching_queues.py
This PR adds a helper class to manage engine operator requests that may come in for various engines held by the same continuous batching scheduler
the main idea is that as `EngineOperator` requests come in, they will be queued in separate Queues key'd by their `EngineOperator`.  The scheduler will then use `ContinuousBatchingQueues.pop_batch()` to select the next most important batch for running.
Right now, the heuristic for the next batch is 1) the queue with longest wait time if it is over 100ms 2) the queue that can fill the largest batch size.  For future work - the scheduler can implement a `select_fn` with more involved heuristics that take into account other worker threads if needed.
**test_plan:**
Unit tests included for basic functionality of `ContinuousBatchingQueue` and …
=> [Continuous Batching] Queue Implementation to support batching grouping and prioritization

src/deepsparse/v2/operators/engine_operator.py, src/deepsparse/v2/schedulers/utils/__init__.py, src/deepsparse/v2/schedulers/utils/continuous_batching_executor.py, tests/deepsparse/v2/schedulers/utils/test_continuous_batching_executor.py
This PR adds a helper class for executing `EngineOperators` using batches popped from `ContinuousBatchingQueues`.
The idea is that this thread can run indefinitely, waiting for a new batch from the `ContinuousBatchingQueues` and running them as available.
The `ContinuousBatchingScheduler` will spin up `num_workers` of these threads and run them indefinitely
**test_plan:**
unit test included
=> [Continuous Batching] Executor thread for running continuous batching

src/deepsparse/v2/schedulers/__init__.py, src/deepsparse/v2/schedulers/continuous_batching_scheduler.py, tests/deepsparse/v2/schedulers/test_continuous_batching_scheduler.py
Uses the utils in #1373 and #1374 to implement a scheduler for continuous batching.
The `ContinuousBatchingScheduler` tracks various `EngineOperators` and manages their input queues with `ContinuousBatchingQueues`.  The scheduler also runs multiple `ContinuousBatchingExecutorThreads` in parallel that consume these queues and actually run the multi-batch engine and return the correct futures from the scheduler `submit`.
**next steps include:**
* integration with KV Cache engine mode for text gen
* implementation of a singleton pattern so that the scheduler can easily be shared across pipelines
* text gen pipeline integration
* more involved heuristic for the `select_fn` to determine execution priority
* server integration
* heavier testing
* README
**test_plan:**
simple single execution …
=> [ContinuousBatching] ContinuousBatchingScheduler Implementation

src/deepsparse/v2/schedulers/continuous_batching_scheduler.py
singleton pattern for continuous batching scheduler is favorable so that engine requests coming from different pipelines are scheduled together and do not interfere with each other. 
this diff provides a simple implementation and extends the docstring with a small example
=> [continuous batching] singleton pattern for scheduler

src/deepsparse/transformers/utils/token_generator.py
Before: regardless of whether `sampling=True or False` we would do `top_k `and `top_p` sampling.
Now: if `sampling=False`, we directly "jump" to the argmax function and avoid any sampling logic.
@horheynm Could you please validate the rest of the logic in `def generate(self, logits: numpy.ndarray)`? In the most complex scenario, we can apply both `top_k`, `top_p`, and `sampling_temperature` sequentially to our logits. Let's make sure that the order in which the sampling functions are applied matches the one defined in HF (I assume this is the original implementation that we want to mimic).
=> [Fix][Text Generation Pipeline] Fix the erroneous sampling logic

src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/yolov8/README.md, tests/deepsparse/transformers/pipelines/integration_tests/configs/gpt_neo.yaml
We are currently not running any integration tests in GHA. As a result, there exists a set of potential errors, that we cannot catch in our CI. This PR adds a very lightweight integration test, that will run on every commit. It hardens the coverage of the `TextGenerationPipeline`.
=> [Test][Text Generation Pipeline] Add a lightweight integration tests (uses `TinyStories-1M`)

docker/Dockerfile
Recently a bug was caught by @mgoin where our nightly docker images were not actually installing nightlies;
This was because the `BRANCH` arg was not redefined b/w stages and docker does not persist arg values across stages;
This PR fixes that
=> [BugFix] Redefine ARG between stages

src/deepsparse/transformers/pipelines/text_generation.py
i built a new HF space and hit this error:
```
File "/home/user/app/app.py", line 150, in generate
for token in inference:
File "/home/user/.local/lib/python3.10/site-packages/deepsparse/transformers/pipelines/text_generation.py", line 568, in _stream_engine_outputs
generation = self._create_generated_text_output(
File "/home/user/.local/lib/python3.10/site-packages/deepsparse/transformers/pipelines/text_generation.py", line 556, in _create_generated_text_output
return GeneratedText(
File "/home/user/.local/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
__pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GeneratedText
finished_reason
Field required …
```
=> [TextGen] Make score and finished_reason fully optional

src/deepsparse/v2/__init__.py, src/deepsparse/v2/operators/__init__.py, src/deepsparse/v2/operators/operator.py, src/deepsparse/v2/operators/registry.py, src/deepsparse/v2/task.py, src/deepsparse/v2/text_generation/pipeline.py
Example using `Operator.create(...)` for the registered text generation pipeline operator 
```python
from deepsparse.transformers.pipelines.text_generation import TextGenerationInput
from deepsparse.v2.operators import Operator
model_path = "hf:mgoin/TinyStories-1M-deepsparse"
pipeline = Operator.create(
model_path=model_path,
prompt_sequence_length=3,
engine_kwargs={"engine_type": "onnxruntime"},
)
def run_requests():
prompts = [["Hello there!", "How are you?"]]
outputs = []
for i in range(len(prompts)):
input_value = TextGenerationInput(
prompt=prompts[i],
generation_kwargs={
"do_sample": False,
"max_length": 20,
},
)
output = pipeline(input_value)
yield output
output = run_requests()
for x in output:
for g in x.generations:
print("\n")
print(g)
```
=> [Pipeline Refactor] Operator Registry

src/deepsparse/transformers/pipelines/text_generation.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
Fix for: https://app.asana.com/0/1205229323407165/1205993428418769/f
```python
model_path = "zoo:opt-1.3b-opt_pretrain-pruned50_quantW8A8"
model_path = "zoo:llama2-7b-gsm8k_llama2_pretrain-pruned80_quantized"
pipeline = Pipeline.create(task="text-generation", model_path=model_path, sequence_length=64)
generations = pipeline(prompt="Hi, my name is Slim", streaming=True)
print(("").join([g.generations[0].text for g in generations]))
```
```bash
.everyoneisamemberofthesamegroup,andthereare10membersinthegroup.
Ifyouareamemberofthegroup,andthereare10membersinthegroup,thenthegroupisdividedinto
```
```bash
. everyone is a member of the same group, and there are 10 members in the group.
If you are a member of the group, and there are 10 members in the group, then …
```
=> [Fix] Appropriate whitespace missing in streaming output for Llama2, Mistral models

src/deepsparse/v2/operators/operator.py, src/deepsparse/v2/pipeline.py, src/deepsparse/v2/text_generation/pipeline.py, src/deepsparse/v2/utils/data.py
- While using the new timer with the new refactored pipeline, engine operator execution was really slow for all cases compared to v1 (ORT, deepsparse with internal kv_cache, deepsparse engine without internal kv_cache)
- After doing some digging, this was due to conditions that were being checked when executing each operator within the subgraphs
- Fixing this issue allows all 3 cases to run with the expected speed (time comparisons were made with the sample scripts shown below)
Multiple Prompts (3) with Multiple Generations (4 per prompt):
| | ORT | Continuous Batching, ORT | Deepsparse with External KV Cache | Continuous Batching, Deepsparse with External KV Cache |  Deepsparse with Internal KV Cache |
| --- | --- |  --- | --- | --- | --- |
| v1 | 58.437 | x| 46.41 | x  | 15.44 |
| v2 | …
=> [Pipeline Refactor] Fix Operator scheduling to fix issue with slow execution 

src/deepsparse/utils/onnx.py, tests/deepsparse/image_classification/test_pipelines.py
Due to those changes: https://github.com/neuralmagic/sparsezoo/pull/389 we need to update the relevant pathways.
=> [Fix] Adapt to the newest SparseZoo interface (and get GHA green again) 

src/deepsparse/v2/pipeline.py
- Adds `create()` method such that `Pipeline.create(...)` can be used to initialize a pipeline
- Uses the Operator registry under the hood
```python
from deepsparse.v2.pipeline import Pipeline
model_path = "hf:neuralmagic/mpt-7b-chat-pruned50-quant"
model_path=model_path,
engine_kwargs={"engine_type": "deepsparse"},
internal_kv_cache=True,
continuous_batch_sizes=[2, 4],
)
```
=> [Pipeline Refactor] Add `Pipeline.create` method to initialize pipelines

src/deepsparse/pipeline.py
- Add in the top level alias functions to `pipeline.py`
```python
from deepsparse import TextGeneration, CodeGeneration, Chat
model_path = "hf:neuralmagic/TinyLlama-1.1B-Chat-v0.4-pruned50-quant-ds"
pipeline = TextGeneration(model_path=model_path)
```
=> [Pipeline Refactor] Add in top level aliases

src/deepsparse/transformers/eval_downstream.py
- Import missed during migration
=> [PIpeline Refactor] Fix eval_downstream import

src/deepsparse/transformers/pipelines/text_generation/__init__.py, src/deepsparse/transformers/pipelines/text_generation/parse_inputs.py, src/deepsparse/transformers/pipelines/text_generation/pipeline.py
- We hadn't yet added in a `parse_inputs` function to  the new `TextGenerationPipeline`. 
- The base `parse_inputs` function previously in `BasePipeline` is covered by the normal operator functionality but for TextGeneration, we do a bit of extra kwarg/arg parsing. This operator handles that additional functionality 
- All integration and unit testing pass
Examples of cases which now work:
With the following pipeline:
```python
model_path=model_path,
engine_type="deepsparse",
internal_kv_cache=True,
)
```
Not explicitly listing `prompt` or `sequences`
```python
output = pipeline(
"What is your favourite snack?", num_return_sequences=2, do_sample=True
)
```
Listing `sequences`:
```python
output = pipeline(
sequences="What is your …
```
=> [Pipeline Refactor][Text Generation] Add `parse_inputs` operator to TextGeneration

src/deepsparse/transformers/pipelines/text_generation/generate_new_token.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
- This commit happened while v2 was being migrated so adding it back to the new pipeline
- `test_text_generation.py` updated to use the new pipeline; skipping tests which are missing features
=> [Text Generation][Pipeline Refactor] Add kv_cache session full check

src/deepsparse/transformers/pipelines/text_generation/process_inputs.py, src/deepsparse/transformers/pipelines/text_generation/process_outputs.py, tests/deepsparse/transformers/pipelines/test_text_generation.py
- This PR was merged while we were working on v2. Involves adding input_tokens to the output for perplexity
- Updates to no longer skip the test for this
=> [Text Generation][Pipeline Refactor] Add input tokens to output for perplexity

src/deepsparse/server/deepsparse_server.py, src/deepsparse/server/server.py, tests/server/test_endpoints.py
- Temporarily disabled `from_files` when migrating the server as our previous solution involved checking the schema for the pipeline. This no longer works as an operator doesn't have to have an input schema 
- Provided a temporary solution as lower priority but wanted to unblock QA. As we migrate more pipelines, we can work on a slightly more sophisticated solution but for now, only `image_classification` has been migrated which also uses v2 and supports`from_files`
- All server tests pass
Tested locally
```
deepsparse.server \
task image_classification \
--model_path "zoo:cv/classification/resnet_v1-50/pytorch/sparseml/imagenet/pruned95-none" \
--port 5543
```
=> [Pipeline Refactor][Server] Enable from files for v2

src/deepsparse/operators/engine_operator.py, src/deepsparse/schedulers/continuous_batching_scheduler.py, src/deepsparse/transformers/pipelines/text_generation/nl_engine_operator.py, src/deepsparse/transformers/pipelines/text_generation/pipeline.py
- Remove the check in `text_generation/pipeline.py` which  disables continuous batching when internal kv cache is enabled
- Update `NLEngineOperator` to use the engine provided as an input, if available, when using internal kv cache. This engine will have the model with the updated batch size, when continuous batching is being used (this is true in general for continuous batching)
- Update step when engines are created within the `continuous_batching_scheduler` specific for the `NLEngineOperator`
=> [Text Generation] Enable continuous batching when internal kv_cache is enabled

src/deepsparse/server/openai_server.py
The OpenAI server was always returning `"usage":{"prompt_tokens":2,"total_tokens":4,"completion_tokens":2}` since it was taking the length of the token_ids dictionary and not one of its members
```
final_res.prompt_token_ids {'input_ids': [1639, 389, 257, 7613], 'attention_mask': [1, 1, 1, 1]}
```
Server command:
```
deepsparse.server --integration openai --task text-generation --model_path hf:mgoin/TinyStories-1M-ds
```
Client command:
```
curl http://localhost:5543/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer dummy" \
-d '{
"model": "hf:mgoin/TinyStories-1M-ds",
"messages": "You are a helpful assistant."
}'
```
Before:
```
{"id":"cmpl-10b937d72d2b4cf382da0c6e54241814","object":"chat.completion","created":1703173842,"model":"hf:mgoin/TinyStories-1M …
```
=> Correct token usage reporting for OpenAI server

src/deepsparse/server/openai_server.py, src/deepsparse/server/protocol.py, tests/server/test_openai.py
The OpenAI `v1/chat/completions` endpoint would fail to properly parse a `request.messages` of the `List[Dict]` format
Server command:
```
deepsparse.server --integration openai --task text-generation --model_path hf:mgoin/TinyStories-1M-ds
```
Client command:
```
curl http://localhost:5543/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer dummy" \
-d '{
"model": "hf:mgoin/TinyStories-1M-ds",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"role": "user",
"content": "Hello!"
}
]
}'
```
Before:
```
{"object":"error","message":"Message role not recognized","type":"invalid_request_error","param":null,"code":null}
```
After:
```
{"id":"cmpl-e3bd5431cc384dab8782254ac0a2f862","object":"chat.completion","created":1703185938,"mod …
```
=> Let OpenAI ChatCompletionRequest accept List[Dict] messages

.github/workflows/test-check.yaml, setup.py, src/deepsparse/server/openai_server.py, src/deepsparse/server/protocol.py, src/deepsparse/transformers/pipelines/text_generation/autoregressive_preprocess_operator.py, src/deepsparse/transformers/pipelines/text_generation/prep_for_prefill.py, tests/server/test_openai.py
Inspired by https://github.com/vllm-project/vllm/pull/1365 and instigated by prefill benchmarking, using the HF Chat Templates hidden within the model's `tokenizer` seems to be a more elegant approach.
From a performance perspective, fastchat's default template adds over 400 tokens as a preamble to chat conversations, **without actually using the right prompt format the model was trained on**! Example below:
```
1. Treasure Hunt: Organize a treasure hunt in your backyard or nearby park. Create clues and riddles for the kids to solve, leading them to hidden treasures and surprises.
2. Science Party: Plan a science-themed party where kids can engage in fun and interactive experiments. You can set up different stations with activities like making slime, erupting volcanoes, or creating simple …
```
=> Replace Fastchat Chat Templates with HF `apply_chat_template`

src/deepsparse/pipeline.py
- For this bug: https://app.asana.com/0/1205229323407165/1206273548252848/f
The following now work:
```python
from deepsparse import TextGeneration
model_1 = TextGeneration(model="hf:mgoin/TinyStories-1M-ds")
model_2 = TextGeneration(model_path="hf:mgoin/TinyStories-1M-ds")
model_path=model_path,
engine_type="deepsparse",
internal_kv_cache=True,
continuous_batch_sizes=[2, 4]
)
model=model_path,
engine_type="deepsparse",
internal_kv_cache=True,
continuous_batch_sizes=[2, 4]
)
```
=> [TextGeneration] Add `model_path` alias

src/deepsparse/transformers/pipelines/text_generation/autoregressive_preprocess_operator.py, src/deepsparse/transformers/pipelines/text_generation/prep_for_prefill.py
- Two logs that were initially set to `info` are now changed to be `debug`
This will address the following ticket: https://app.asana.com/0/1205229323407165/1206269382548635/f
=> [TextGeneration] Set scary logs to `debug`

src/deepsparse/evaluation/cli.py, src/deepsparse/evaluation/evaluator.py, src/deepsparse/evaluation/integrations/lm_evaluation_harness.py, src/deepsparse/evaluation/results.py, src/deepsparse/evaluation/utils.py, tests/deepsparse/evaluation/integrations/__init__.py, tests/deepsparse/evaluation/integrations/test_lm_evaluation_harness.py, tests/deepsparse/evaluation/test_evaluator.py, tests/deepsparse/evaluation/test_registry.py, tests/deepsparse/evaluation/test_results.py, tests/deepsparse/evaluation/test_utils.py
This PR fixes a bug where `src.` was included in front of imports; this is faulty because once the package is built `src.deepsparse` becomes invalid
Ran the affected tests locally
```
$ pytest -vv tests/deepsparse/evaluation                                                                                                                                 (main|✚10…1)
================================================================================ test session starts =================================================================================
platform linux -- Python 3.11.5, pytest-7.4.4, pluggy-1.3.0 -- /home/rahul/venvs/.base_venv/bin/python3.11
cachedir: .pytest_cache
rootdir: /home/rahul/projects/deepsparse
configfile: pyproject.toml
plugins: flaky-3.7.0
collected 28 items …
```
=> [BugFix] Remove `src.` from imports

src/deepsparse/server/cli.py, src/deepsparse/server/config.py, src/deepsparse/server/server.py, tests/server/test_app.py
- The integration value defined in the server config was being ignored and the cli argument was only being considered
- Update to use both
- Also update tests and small clean-up
- For this ticket: https://app.asana.com/0/1205229323407165/1206280777419100/f
- All server tests pass
The following config file will create an openai server:
```yaml
num_workers: 1
num_streams: 1
integration: openai
endpoints:
model: "hf:mgoin/TinyStories-1M-ds"
kwargs:
{"continuous_batch_sizes": [4, 8, 16], "force_max_tokens": True}
```
=> [Server] Use the integration field when starting a server

src/deepsparse/benchmark/benchmark_pipeline.py
- While using `benchmark_pipeline`, found a small bug in reported stats where we were incorrectly reporting the number of keys in the dictionary, not the number of iterations for which inference ran
=> [Benchmark] Fix number of iterations reported

src/deepsparse/schedulers/continuous_batching_scheduler.py, src/deepsparse/server/server.py, tests/deepsparse/schedulers/test_continuous_batching_scheduler.py
- This PR addresses this ticket: https://app.asana.com/0/1205229323407165/1206269161795436/f
- We were using concurrent futures for async calls that cannot be awaited within the `continuous_batching_scheduler`. For all other operators, we were using `asyncio` Futures. Using the incorrect future seemed to block the scheduler queue from ever growing > 1.
-  This PR updates the future to check if we're running async or not (by checking if an async loop is present) and using the correct Future accordingly 
- Tested locally, we are now getting batch_size > 1
```yaml
num_workers: 1
num_streams: 1
endpoints:
model: "hf:mgoin/TinyStories-1M-ds"
kwargs:
{"continuous_batch_sizes": [4, 8, 16], "force_max_tokens": True}
```
Using the following code, we can see batch_size > 1 …
=> [TextGeneration] Use appropriate future within `continuous_batching_scheduler`

setup.py, src/deepsparse/evaluation/cli.py
This PR fixes a few minor bugs found in `deepsparse.eval`
`deepsparse.eval` was pointing to the wrong script for it's cli
```bash
rahul at office-desktop in ~/projects/deepsparse (fix-bugs) (.base_venv) 
$ deepsparse.eval --help                                                                                                                                                (fix-bugs|✔)
File "/home/rahul/venvs/.base_venv/bin/deepsparse.eval", line 5, in <module>
from deepsparse.evaluate.evaluator.cli import main
ModuleNotFoundError: No module named 'deepsparse.evaluate'
```
The `engine_type` argument was passing `None` to click.Choice, which is invalid.
This can be fixed by passing a list of valid choices to click.Choice
```bash
$ deepsparse.eval --help …
```
=> [BugFixes] Fix Broken `deepsparse.eval`

src/deepsparse/benchmark/benchmark_model.py
Tested two entrypoints for deepsparse.benchmark. One used internal KV and other used external. Goal is to always use internal KV.
1. Python
```python3
from deepsparse.benchmark.benchmark_model import benchmark_model
stub = "zoo:mistral-7b-gsm8k_mistral_pretrain-pruned80"
results = benchmark_model(stub)
print(results)
```
2. CLI
```bash
deepsparse.benchmark "zoo:mistral-7b-gsm8k_mistral_pretrain-pruned80"
```
1. Python
```json
{
"engine":"deepsparse.engine.Engine:\n\tonnx_file_path: /home/george/.cache/sparsezoo/neuralmagic/mistral-7b-gsm8k_mistral_pretrain-pruned80/deployment/model.onnx\n\tbatch_size: 1\n\tnum_cores: 32\n\tnum_streams: 1\n\tscheduler: Scheduler.default\n\tfraction_of_supported_ops: 1.0\n\tcpu_avx_type: avx2\n\tcpu_vnni: False",
"version":"1.7.0.20240104", …
```
=> Use Int KV Cache as default for deepsparse.benchmark

src/deepsparse/transformers/pipelines/text_generation/nl_engine_operator.py
- When updating the NLEngineOperator to process batch_size > 1 with internal_kv_cache enabled (for continuous_batching), one line was missed in the update PR. This PR fixes this issue and also cleans up some of the conditions
- This will also fix this ticket: 
https://app.asana.com/0/1205229323407165/1206239324632274/f
=> [TextGeneration] Fix internal kv_cache update for batch_size > 1

examples/llmperf/README.md, examples/llmperf/config.yaml
Simple example walking through how to run LLMPerf benchmarks and how to analyze the output statistics
=> Add LLMPerf example for DeepSparse LLM Server

src/deepsparse/evaluation/integrations/__init__.py, src/deepsparse/evaluation/integrations/lm_evaluation_harness.py
This PR fixes a few bugs found while updating the eval framework:
1) `sequence_length` is no longer exposed at the pipeline level
```python
task="text-generation",
model_path="zoo:mpt-7b-mpt_pretrain-base_quantized",
)
assert hasattr(pipeline, "sequence_length")
```
```bash
File "/home/rahul/projects/deepsparse/local.py", line 12, in <module>
assert hasattr(pipeline, "sequence_length")
AssertionError
>>> 
```
Fix: workaround relies on `pipeline.ops["single_engine"].sequence_length`
2) `deepsparse.eval` requires a specific commit from lm-eval-harness for now, updating the install message to reflect that
=> [BugFixes] `deepsparse.eval`

src/deepsparse/evaluation/integrations/lm_evaluation_harness.py, src/deepsparse/transformers/pipelines/text_generation/pipeline.py
This PR exposes `sequence_length` as a Pipeline level property
Test Code:
```python
task="text-generation",
model_path="zoo:mpt-7b-mpt_pretrain-base_quantized",
)
assert hasattr(pipeline, "sequence_length")
```
Was failing before, but passes after this PR
=> [Add] sequence length to text gen pipelines

src/deepsparse/benchmark/benchmark_model.py, src/deepsparse/debug_analysis.py
It will default to 1 or NM_BENCHMARK_KV_TOKENS, if it is set
```
> deepsparse.benchmark hf:mgoin/TinyStories-1M-ds --num-kv-cache-tokens 1 -ncores 1 -q
Fetching 11 files: 100%|██████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 15666.33it/s]
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.7.0.20231210 COMMUNITY | (99472380) (release) (optimized) (system=neon, binary=neon)
Original Model Path: hf:mgoin/TinyStories-1M-ds
Batch Size: 1
Scenario: sync
Throughput (items/sec): 1158.0933
Latency Mean (ms/batch): 0.8611
Latency Median (ms/batch): 0.8375
Latency Std (ms/batch): 0.0655
Iterations: 11581
> deepsparse.benchmark hf:mgoin/TinyStories-1M-ds --num-kv-cache-tokens 1000 -ncores 1 -q
Fetching 11 files: …
```
=> Add `--num-kv-cache-tokens` to benchmarking scripts

src/deepsparse/benchmark/benchmark_pipeline.py, src/deepsparse/middlewares/__init__.py, src/deepsparse/middlewares/timer_middleware.py, src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/text_generation/pipeline.py, src/deepsparse/utils/time.py, tests/test_pipeline_benchmark.py
- Update `benchmark_pipeline` such that it can work for both v1 and v2 pipelines. v1 uses a different timer compared to v2 and the changes in this PR allow support for both. v2 also requires `middleware` to be passed to the pipeline constructor when creating it 
- Clean-up the middleware code. There are a lot of keys being passed around that were stored as strings. To have one source of truth, the middleware/timer files were updated to include the constants 
- Also, exposes the `input_schema` and `output_schema` at the pipeline level
- The following both work for v1 and v2 when running the benchmark pipeline:
For text_generation:
```bash
deepsparse.benchmark_pipeline text_generation  "hf:mgoin/TinyStories-1M-ds"
```
Output:
```bash
2024-01-08 22:01:22 deepsparse.benchmark.helpers WARNING …
```
=> [timer][benchmark_pipeline] Update the `benchmark_pipeline` to work with v1 and v2; clean-up middleware/timer_middleware

src/deepsparse/transformers/schemas/text_generation_schemas.py, src/deepsparse/transformers/utils/helpers.py
- Previously, if the user provided anything for the `generation_config` argument, we always returned a `GenerationConfig` object for this case
- Now if the user provides the `GenerationConfig` object, that is the only case where we return the object without using deepsparse defaults
- If the user provides a dictionary, we create a GenerationConfig object, override with deepsparse defaults, and then set any attributes provided by the user in the dictionary
- This is aided through the conversion of the defaults into a dataclass
- All other workflows remain the same (i.e providing `generation_kwargs` or cli arguments which have always used deepsparse defaults)
Also takes care of this discussion: https://app.asana.com/0/1205229323407165/1206280624568198/f
=> [TextGeneration] Update defaults to always start with deepsparse defaults when using the `generation_config` arg

src/deepsparse/pipeline.py, src/deepsparse/schedulers/continuous_batching_scheduler.py
- This fixes the `Future` being used by the `continuous_batching_scheduler` in async pathways (i.e the server) 
- Last PR to update the future to be an asyncio.Future in the `continuous_batching_scheduler` had the right idea but just applied in the incorrect spot
- Provides > 3x speedup in tokens/second processed for this ticket: https://app.asana.com/0/1205229323407165/1206353069568391/f
Inspiration: https://github.com/python/cpython/blob/b331381485c1965d1c88b7aee7ae9604aca05758/Lib/asyncio/base_events.py#L871
```yaml
num_workers: 1
endpoints:
model: "hf:neuralmagic/MiniChat-1.5-3B-pruned50-quant-ds"
kwargs:
{"continuous_batch_sizes": [2,3,4,5,6,7,8,16], "force_max_tokens": True}
```
Client
```python
import requests
from threading import Thread
import time, …
```
=> [server][Pipeline] fix async future being used by continuous_batching

src/deepsparse/server/openai_server.py, src/deepsparse/server/protocol.py, src/deepsparse/transformers/schemas/text_generation_schemas.py, tests/server/test_openai.py
Found through lm-evaluation-harness since for the OpenAI Completion interface they make requests using raw token_ids
OAI docs reference: https://platform.openai.com/docs/api-reference/completions
> prompt: The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays.
Example request during `gsm8k` evaluation:
```
{'model': 'hf:mgoin/llama-2-7b-gsm8k-pruned60-quant-ds', 'prompt': [[1, 894, 29901, 21828, 18577, 29871, 29929, 29900, 9814, 273, 21425, 322, 29871, 29946, 29900, 28145, 5697, 348, 3173, 393, 9814, 273, 21425, 29889, 1128, 1784, 18281, 947, 540, 8024, 3001, 29973, 13, 22550, 29901]], 'max_tokens': 256, 'stop': ['<|endoftext|>'], 'seed': 1234, 'temperature': 0.0}
```
Server command:
```
deepsparse.server --integration …
```
=> Add support for tokenized prompt input for CompletionRequest

src/deepsparse/loggers_v2/utils.py, tests/deepsparse/loggers_v2/test_util.py
Given config.yaml, the contents may contain default function or class name (eg. max, everage, PythonLogger,...). The PR has utils to import
=> [V2 Logger]  utils for import

src/deepsparse/loggers_v2/logger_manager.py
Added doc string, made entrypoints async
=> [V2 Loggers] logger manager patch

src/deepsparse/loggers_v2/__init__.py, src/deepsparse/loggers_v2/config.py, tests/logger_v2/config.py, tests/logger_v2/test_config.py
Config yaml file has five top level properties: version,  logging, system, performance and metric. 
version is always 2, since its for v2 pipeline
logging is the name of the defined logging (class LoggingFoo: here the name is LoggingFoo) which are singletons (one instance per any Name). 
Sys, Perf and Met are the three entry points to use the Logger. 
System is for default python (import logging) logging
Performance is for logging any hardware, benchmark,..etc metric-related log (thing that are already defined).
Metric is for input related logging (output value based on inputs).
If logging has any args for instantiation, one can define as 
```yaml
loggers:
logger_id:
name: FooLogger
arg1: 1
arg2: 2
```
For the three entry points,  the top level  after the root logger (system, metric, …
=> [V2 Loggers] config file

src/deepsparse/loggers_v2/root_logger.py, tests/logger_v2/test_root_logger.py
Three types of root loggers: system, performance and metric. All root loggers have shared leaf loggers (bc they are singleton). Each root loggers have their own FrequencyFilter. Calling `.log(...)` will call leaf loggers after the filtering rules passes.
=> [V2 Logger] root logger

src/deepsparse/transformers/pipelines/text_generation/autoregressive_preprocess_operator.py, src/deepsparse/transformers/pipelines/text_generation/compile_generations.py, src/deepsparse/transformers/pipelines/text_generation/generate_new_token.py, src/deepsparse/transformers/pipelines/text_generation/multi_engine_prefill_operator.py, src/deepsparse/transformers/pipelines/text_generation/pipeline.py, src/deepsparse/transformers/pipelines/text_generation/pipeline_no_kv_cache.py, src/deepsparse/transformers/pipelines/text_generation/prep_for_generation.py, src/deepsparse/transformers/schemas/text_generation_schemas.py, src/deepsparse/transformers/utils/helpers.py, tests/deepsparse/transformers/pipelines/test_text_generation.py, tests/deepsparse/transformers/text_generation/unit/text_generation/test_pipeline_no_kv_cache.py, tests/deepsparse/transformers/text_generation/unit/text_generation/test_token_generation.py
=> [Cherry-Pick] for 1.7

src/deepsparse/server/deepsparse_server.py, src/deepsparse/server/openai_server.py, src/deepsparse/server/server.py
- For this ticket: https://app.asana.com/0/1205229323407165/1206269382450968/f
- Previously, the server always initialized a `Context` object as all pipelines used the `MultiModelEngine` which requires a `Context` input. `Context` always uses the `elastic` scheduler
- With this PR, for the case where `continuous_batch_sizes` are provided, a `Context` object is not used during pipeline initialization and a single stream scheduler is selected. 
- This  prevents us from using the `MultiModelEngine` for this case but any other pipeline initialized without `continuous_batch_sizes` will use `Context/MultiModelEngine`
=> [server] Disable the elastic scheduler when continuous batching is enabled

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/text_generation/autoregressive_preprocess_operator.py
- To address this ticket: https://app.asana.com/0/1205229323407165/1206459001098561
- Also update condition for kv cache capacity check to prevent repeat check
=> [TextGeneration] Fix initialization; don't try v1 init for text gen

src/deepsparse/pipeline.py, src/deepsparse/server/deepsparse_server.py, src/deepsparse/server/openai_server.py, src/deepsparse/server/server.py, src/deepsparse/transformers/pipelines/text_generation/autoregressive_preprocess_operator.py
Cherry Picks for LLM bugs:
- #1569 
- #1571
=> [1.7 Cherry Picks]

src/deepsparse/benchmark/benchmark_model.py, src/deepsparse/utils/onnx.py
Fix for: https://app.asana.com/0/1206109050183159/1206490681470513/f
The model `zoo:llama2-7b-open_platypus_orca_llama2_pretrain-pruned40_quantized` does not have the sequence length set internally in the onnx model (@alexm-nm is that something that we expect in the first place)? Because we cannot deduce this parameter, we are crashing with a very obscure message. This PR adds more verbose termination, that guides the user towards the right action (providing the sequence length manually)
=> [Fix] ONNX model benchmarking when no sequence_length inferred from the model

src/deepsparse/__init__.py, src/deepsparse/analyze.py
Add missing analyze function and top level callable
```python
from deepsparse import analyze
analysis = analyze("zoo:mobilenet_v1-1.0-imagenette-base")
analysis.summary().pretty_print()
```
Output:
```bash
$ python local/descriptions/analyze_bug.py                                                                   (add-analyze-callable|✚2…3⚑1)
2024-02-02 05:08:18 deepsparse.analyze INFO     Analysis complete, collating results...
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.7.0.20240104 COMMUNITY | (86c38139) (release) (optimized) (system=avx512, binary=avx512)
Node Timings for Benchmark # 1:
NODE_NAME                      AVG_RUNTIME                    
Conv_55                        0.02                           
Conv_60                        0.04 …
```
=> [BugFix] Add analyze callable

tests/deepsparse/schedulers/test_continuous_batching_scheduler.py, tests/deepsparse/schedulers/utils/test_continuous_batching_executor.py, tests/deepsparse/transformers/text_generation/integration_tests/test_llms.py
- Temporarily disabled due to potential source for jenkins seg fault
- As those tests are now passing/not running into seg fault errors, update to add back these tests
=> [Continuous Batching][Text Generation] Add back continuous batching tests

src/deepsparse/__init__.py
adds support for:
```python
from deepsparse import benchmark_model, benchmark_pipeline
```
=> add top level benchmark imports

src/deepsparse/pipeline.py, src/deepsparse/server/cli.py
- Add a quick helper function which supports non-kwarg for model_path when using the `TextGeneration` pathway
- For this ticket: https://app.asana.com/0/1206109050183159/1206524727025314/f
The following now works:
```python
from deepsparse import TextGeneration
model_path = "hf:mgoin/TinyStories-1M-ds"
pipe = TextGeneration(model_path)
```
This still works:
```python
model_path  = TextGeneration(model_path=model_path)
```
=> [TextGeneration] Add helper function to parse model path from args

src/deepsparse/server/cli.py
- With our current `click` set-up, to get the use case described in this ticket (shown below): https://app.asana.com/0/1206109050183159/1206524727025314/f 
```bash
deepsparse.server \
"zoo:llama2-7b-ultrachat200k_llama2_pretrain-pruned50_quantized" \
--integration openai
```
This PR allows us to get the following cli command:
```bash
deepsparse.server --integration openai "hf:mgoin/TinyStories-1M-ds"
```
We can run the following commands with the current set-up:
```bash
deepsparse.server --task text_generation --model_path "hf:mgoin/TinyStories-1M-ds"
deepsparse.server --model_path "hf:mgoin/TinyStories-1M-ds" --integration openai
deepsparse.server --task text_generation "hf:mgoin/TinyStories-1M-ds"
deepsparse.server --intergration openai --task text_generation …
```
=> [server] Add `model` argument to server cli

src/deepsparse/pipeline.py, src/deepsparse/server/cli.py
=> [Cherry Pick] 1.7 TextGen and Server UX Updates 

src/deepsparse/__init__.py
makes sure that top level benchmark_* imports are the functions, not modules (ie file names)
```python
>>> from deepsparse import benchmark_model, benchmark_pipeline
>>> benchmark_model
<function benchmark_model at 0x7f4b5434faf0>
>>> benchmark_pipeline
<function benchmark_pipeline at 0x7f4b6b368430>
```
=> make sure benchmark_* imports are the functions, not modules

src/deepsparse/__init__.py
makes sure that top level benchmark_* imports are the functions, not modules (ie file names)
```python
>>> from deepsparse import benchmark_model, benchmark_pipeline
>>> benchmark_model
<function benchmark_model at 0x7f4b5434faf0>
>>> benchmark_pipeline
<function benchmark_pipeline at 0x7f4b6b368430>
```
=> [cherry-pick] make sure benchmark_* imports are the functions, not modules (#1593)

src/deepsparse/server/README.md, src/deepsparse/server/cli.py, src/deepsparse/transformers/README.md, src/deepsparse/yolact/README.md, src/deepsparse/yolo/README.md
- We no longer support the `task` or `config-file` subcommands/have been deprecated for a while
- Remove from server cli and update readmes 
- Also, slight update to the pathway for the new UX
=> [server] Update readmes to no longer use the deprecated pathway + update pathway as per new UX docs

src/deepsparse/evaluation/integrations/perplexity.py, src/deepsparse/transformers/metrics.py, src/deepsparse/transformers/utils/eval_helpers.py, tests/deepsparse/evaluation/integrations/test_perplexity.py
```bash
deepsparse.evaluate hf:mgoin/TinyStories-1M-deepsparse --integration perplexity --dataset wikitext2 --limit 2 --batch_size 2 --max_sequence_length 128
2024-02-06 18:14:27 deepsparse.evaluation.cli INFO     Creating deepsparse pipeline to evaluate from model path: hf:mgoin/TinyStories-1M-deepsparse
2024-02-06 18:14:27 deepsparse.evaluation.cli INFO     Datasets to evaluate on: ['wikitext2']
Batch size: 2
Splits to evaluate on: None
Metrics to evaluate on: None
Additional integration arguments supplied: {'limit': 2, 'max_sequence_length': 128}
Fetching 11 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 149796.57it/s]
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.7.0.20240104 …
```
=> [DeepSparse Evaluation API] Perplexity eval support for `openai_humaneval`, `c4`, `wikitext2`

setup.py, src/deepsparse/evaluation/cli.py, src/deepsparse/evaluation/evaluator.py, src/deepsparse/evaluation/integrations/__init__.py, src/deepsparse/evaluation/integrations/lm_evaluation_harness.py, src/deepsparse/evaluation/integrations/perplexity.py, src/deepsparse/evaluation/registry.py, src/deepsparse/evaluation/results.py, src/deepsparse/evaluation/utils.py, src/deepsparse/transformers/metrics.py, src/deepsparse/transformers/utils/eval_helpers.py, tests/deepsparse/evaluation/integrations/test_lm_evaluation_harness.py, tests/deepsparse/evaluation/integrations/test_perplexity.py, tests/deepsparse/evaluation/test_evaluator.py
=> [Cherry-Pick][Feature Branch][DeepSparse Evaluation API] Update lm-eval, perplexity, additional datasets

setup.py, src/deepsparse/clip/zeroshot_pipeline.py, src/deepsparse/server/openai_server.py, src/deepsparse/transformers/metrics.py, src/deepsparse/utils/data.py, tests/server/test_openai.py
Cherry Pick for #1561 
```bash
Python 3.11.7 (main, Dec  8 2023, 18:56:57) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepsparse.cpu import cpu_details, cpu_architecture
>>> 
KeyboardInterrupt
>>> 
```
=> [Cherry Pick] Remove scipy by implementing log_softmax (#1561)

src/deepsparse/benchmark/benchmark_pipeline.py
- Middleware is a pipeline_kwarg required in the `benchmark_pipeline` 
- When an optional export_path is provided, all pipeline_kwargs are saved in a json file 
-  This fails for the middleware manager, which cannot be saved as a json
- For this ticket: https://app.asana.com/0/1206109050183159/1206622145453069/f
=> [benchmark_pipeline] Update the export dict to remove the middleware key

src/deepsparse/evaluation/integrations/lm_evaluation_harness.py, src/deepsparse/evaluation/utils.py
=> Damian's Cherry Pick

src/deepsparse/evaluation/cli.py
Originally this PR was meant to fix evaluation results not being displayed/saved anywhere, but that is working as intended, took this opportunity to update misleading command in cli docstring, + added MODEL_PATH descripton for the user (now this gets displayed when `--help` is invoked)
```bash
deepsparse.evaluate /home/rahul/TinyStories-1M-ds -i lm-eval-harness --dataset hellaswag --limit 10 
2024-02-20 16:49:55 __main__     INFO     Creating deepsparse pipeline to evaluate from model path: /home/rahul/TinyStories-1M-ds
2024-02-20 16:49:55 __main__     INFO     Datasets to evaluate on: ['hellaswag']
Batch size: 1
Splits to evaluate on: None
Metrics to evaluate on: None
Additional integration arguments supplied: {'limit': 10}
/home/rahul/projects/deepsparse/.venv/lib/python3.11/site-package …
```
=> [Update] `deepsparse.evaluate` docstring

src/deepsparse/analyze.py
Propagates the name change; needs sparsezoo PR https://github.com/neuralmagic/sparsezoo/pull/459 and https://github.com/neuralmagic/sparsezoo/pull/460 to land
=> [Bugfix] propagate name change of legacy sparsezoo/analyze analyze_v1

src/deepsparse/evaluation/integrations/__init__.py
Upgrading lm-eval to `0.4.1` works as expected
```bash
deepsparse.evaluate ~/TinyStories-1M-ds  -i lm-eval-harness -d hellaswag --limit 10                                          (main|…4⚑2)
2024-02-23 09:38:21 deepsparse.evaluation.cli INFO     Creating deepsparse pipeline to evaluate from model path: /home/rahul/TinyStories-1M-ds
2024-02-23 09:38:21 deepsparse.evaluation.cli INFO     Datasets to evaluate on: ['hellaswag']
Batch size: 1
Splits to evaluate on: None
Metrics to evaluate on: None
Additional integration arguments supplied: {'limit': 10}
/home/rahul/projects/deepsparse/.venv/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. …
```
=> [Upgrade] lm-eval to 0.4.1

src/deepsparse/evaluation/cli.py
The eval docs pass in `datasets` whereas cli script was expecting `dataset`
Updated cli to accept `datasets` which also conforms with `sparseml.evaluate`
=> [bug] Use datasets as expected by docs

src/deepsparse/evaluation/cli.py
Cherry pick for #1622 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206680574454419
=> [Cherry Pick] Use datasets as expected by docs

src/deepsparse/transformers/pipelines/text_generation/prep_for_generation.py, src/deepsparse/transformers/pipelines/text_generation/process_outputs.py
Tested code:
```python
import deepsparse
MODEL_ID = "hf:nm-testing/llama2-7B-sparse70-retrained-ultrachat200k-pruned70-smoothquant-ds"
#MODEL_ID = "zoo:mistral-7b-ultrachat200k_mistral_pretrain-pruned40_quantized"
pipe = deepsparse.Pipeline.create(
task="text-generation",
model_path=MODEL_ID,
sequence_length=512,
prompt_sequence_length=16,
)
message = "Once upon a time"
conversation = []
conversation.append({"role": "user", "content": message})
formatted_conversation = pipe.tokenizer.apply_chat_template(
conversation, tokenize=False, add_generation_prompt=True
)
generation_config = {
"max_new_tokens": 100,
}
inference = pipe(
sequences=formatted_conversation,
generation_config=generation_config,
streaming=True,
)
for token in inference:
print(token.generations[0].text, end="")
```
Output: …
=> [TextGeneration] Fix llama tokenizer

setup.py, src/deepsparse/transformers/pipelines/text_generation/prep_for_generation.py, src/deepsparse/transformers/pipelines/text_generation/process_outputs.py, src/deepsparse/version.py, tests/deepsparse/pipelines/test_pipeline.py, tests/server/test_legacy_loggers.py
=> [TextGeneration] Fix llama tokenizer (#1635)

docs/use-cases/README.md, docs/use-cases/cv/embedding-extraction.md, docs/use-cases/cv/image-segmentation-yolact.md, docs/use-cases/cv/object-detection-yolov5.md, docs/use-cases/general/scheduler.md, docs/use-cases/nlp/question-answering.md, docs/use-cases/nlp/sentiment-analysis.md, docs/use-cases/nlp/text-classification.md, docs/use-cases/nlp/token-classification.md, docs/use-cases/nlp/transformers-embedding-extraction.md, docs/use-cases/nlp/zero-shot-text-classification.md, examples/ultralytics-yolo/ultralytics-readmes/deepsparse-readme.md
Many doc files were still using `'http://0.0.0.0:5543/predict'` as the server inference endpoint, which should now be `'http://0.0.0.0:5543/v2/models/TASK_NAME/infer'`
=> Update server docs to use v2 infer endpoints
