neuralmagic/deepsparse

docs/source/debugging-optimizing/numactl-utility.md, src/deepsparse/engine.py
Some of the documentation wrt. number of sockets was out of date.  These changes should reflect the current state of things.
=> Fix documentation related to number of sockets

examples/huggingface-transformers/benchmark.py, examples/huggingface-transformers/pipelines.py, examples/huggingface-transformers/squad_inference.py
simple app to demonstrate real time SQuAD inference and display results incrementally in the terminal
=> terminal based inference app for SQuAD QA inferenfce

examples/ultralytics-yolo/deepsparse_utils.py, examples/ultralytics-yolo/server.py
This PR will download a Yolo model from if a SparseZoo stub is given as model path
=> BugFix:Download model if stub

examples/huggingface-transformers/squad_eval.py, examples/ultralytics-yolo/README.md, examples/ultralytics-yolo/annotate.py
This PR fixes a few typos in main, to rebase other branches off of
=> Refactor:Fixed typos and grammar

examples/huggingface-transformers/README.md, examples/huggingface-transformers/benchmark.py, examples/huggingface-transformers/server.py, examples/huggingface-transformers/squad_eval.py, examples/huggingface-transformers/squad_inference.py
This PR updates the an old BERT stub `zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned-moderate` to `zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned-aggressive_98`
And also Updates some other older stubs in README.md
=> Refactor:updated old stubs

setup.py, src/deepsparse/cpu.py
updates to messaging for check_hardware command for quickly validating DeepSparse compatibility for model execution
=> Jfinks chk hardware messaging

README.md, examples/huggingface-transformers/requirements.txt, setup.py, src/deepsparse/benchmark_model/README.md, src/deepsparse/benchmark_model/benchmark_model.py, src/deepsparse/transformers/__init__.py, src/deepsparse/transformers/server/main.py
=> [cherry-pick] release/0.10 updates 1/21/22

src/deepsparse/benchmark_model/README.md
Standardizing title font size and emoji location
=> Benchmark update

src/deepsparse/transformers/eval_downstream.py
* Update label mapping for deepsparse.transformers.eval_downstream
* Fix MNLI as well
=> [cherrypick] Update label mapping for deepsparse.transformers.eval_downstream (#323)

README.md
Fixing a dead url on root readme.
=> FIX - bad url

src/deepsparse/cpu.py
=> Fix typo in cpu.py

src/.gitignore
=> adding neon binaries to git ignore

src/deepsparse/image_classification/pipelines.py, src/deepsparse/image_classification/schemas.py, src/deepsparse/server/main.py, src/deepsparse/yolo/schemas.py
Tested on local swagger UI server.
When passing a single image of a goldfish I get the response:
```
{
"labels": [
392
],
"scores": [
12.067000389099121
]
}
```
which corresponds to ImageNet's `rock beauty, Holocanthus tricolor'`, a fish very similar to goldfish, so I guess this validates the result (haha).
Cannot process more than one image atm, see the bug described below.
=> DeepSparse server to accept UploadFiles 

examples/aws-sagemaker/README.md
Brought up the `requirements` section to the top of page so users now see reqs more clearly.
=> Quick-Fix SageMaker readme

setup.py
* Add click to deepsparse root level dependencies
=> [Cherry-pick]Add click to deepsparse root level dependencies (#424)

Makefile, tests/test_multi_engine.py
These tests take about 90 seconds to  run on my 18 core computer.
=> Added unit tests for MultiModelEngine

src/deepsparse/image_classification/pipelines.py
see: https://github.com/neuralmagic/deepsparse/pull/472
=> Cherry pick: Fix small bug incurred by top_k predictions functionality in IC pipeline.

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/pipeline.py, src/deepsparse/transformers/pipelines/question_answering.py, src/deepsparse/transformers/pipelines/text_classification.py, src/deepsparse/transformers/pipelines/token_classification.py
This PR update sequence_length parameter documentation to mention bucketing as well as adding proper type hints
=> Update sequence_length parameter docs to mention bucketing

src/deepsparse/yolact/README.md
Add Sparseml export flow to yolact docs
=> Add sparseml export pathway to deepsparse yolact docs

src/deepsparse/pipeline.py, src/deepsparse/transformers/pipelines/mnli_text_classification.py, src/deepsparse/transformers/pipelines/zero_shot_text_classification.py
No num_sequences
batch size is engine batch size
if labels given, then batch size % labels == 0
if no labels, require batch size == 1
=> Remove num sequences

src/deepsparse/yolact/README.md
This PR:
- Creates yolact doc in the root directory of the integration
**Test Plan:**
_Manual_
_Automated_
N/A
=> Yolact docs

src/deepsparse/server/main.py
Before this PR invoking `deepsparse.server --help` gave a hardcoded task list as follows:
```bash
--task TEXT                     The task the model_path is serving. For
example, one of: question_answering,
text_classification, token_classification.
Ignored if config file is supplied.
```
This PR updates `--task` field to a `click.Choice` type argument that gives good error handling for unsupported tasks + a nice display message with all tasks:
```bash
--task [custom|question_answering|qa|text_classification|glue|sentiment_analysis|token_classification|ner|zero_shot_text_classification|embedding_extraction|image_classification|yolo|yolact|information_retrieval_haystack|haystack]
The task the model_path is serving.
```
=> Update `deepsparse.server` to display task list programmatically

src/deepsparse/transformers/pipelines/mnli_text_classification.py
Noted by @bfineran this PR makes it clearer that the brackets are meant to be displayed, and not a malformed template.
=> place quotes around brackets

src/deepsparse/server/main.py
=> Cherry pick server tasks display message enhancement

src/deepsparse/yolo/README.md
Update readme to reflect working command
=> Remove trailing `\`

src/deepsparse/pipeline.py
This PR removes duplicate line 153 as unearthed by @derekk-nm, it's the same as line 150
=> Remove duplicate line 153

src/deepsparse/server/main.py
=> [cherry-pick] Enabling hypenated task names in deepsparse.server (#567)

setup.py, src/deepsparse/image_classification/README.md, src/deepsparse/image_classification/schemas.py, src/deepsparse/server/main.py, src/deepsparse/server/utils.py, src/deepsparse/transformers/helpers.py, src/deepsparse/yolact/pipelines.py, src/deepsparse/yolact/schemas.py, src/deepsparse/yolact/utils/annotate.py, src/deepsparse/yolo/pipelines.py, src/deepsparse/yolo/schemas.py, tests/deepsparse/pipelines/test_schemas_from_files.py, tests/deepsparse/transformers/test_helpers.py
Cherry picks for PR #521 and #574
=> Cherry picks bugfixes server.files tokenizer.json

src/deepsparse/image_classification/schemas.py, src/deepsparse/pipelines/computer_vision.py, src/deepsparse/yolact/schemas.py, src/deepsparse/yolo/schemas.py, tests/deepsparse/pipelines/test_computer_vision_pipelines.py
Rename: `cv.py` --> `computer_vision.py`
Rename: `CVSchema` --> `ComputerVisionSchema`
=> CV schema rename

src/deepsparse/yolo/pipelines.py
This PR fixes a bug; and makes `YOLO` pipeline more robust, essentially when a `numpy` array was passed via annotate script it is send in a channels first format, when we try to resize this image using opencv, an error was thrown; the current PR always makes the channels last before resizing hence fixing the bug. Tested with the following:
```bash
deepsparse.object_detection.annotate --source test_images/basilica.jpg
```
output:
```bash
❯ deepsparse.object_detection.annotate --source test_images/basilica.jpg
2022-08-18 11:27:05 deepsparse.utils.annotate INFO     Results will be saved to annotation-results/deepsparse-annotations
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 1.1.0.20220816 COMMUNITY EDITION (c1e95a75) (release) (optimized) (system=avx512, …
```
=> Fixed condition where a single numpy array was passed

src/deepsparse/yolo/pipelines.py
=> [Cherry-Pick]Fixed condition where a single numpy array was passed in Yolo

integrations/haystack/README.md
@rahul-tuli Noticed some typos, so I corrected those and added performance metrics using a pruned and quantized model.
=> Haystack readme: fix typos, better performance metrics

src/deepsparse/transformers/haystack/nodes.py
This PR converts the haystack pipeline's old sequential execution with dynamic batch (https://github.com/neuralmagic/deepsparse/pull/604)
I regression tested by rerunning all the example prompts in the IR writeup and confirming that the values are the same as they were before the changes.
DeepSparseEmbeddingRetriever run times
| Num samples | Before (s) | After (s) |
|-|-|-|
| 1 | 0.062 | 0.026 |
| 10 | 0.019 | 0.013 |
| 100 | 0.175 | 0.112 |
| 1000 | 5.01 | 2.83 |
| 5000 | 29.1 | 13.9 |
=> Information Retrieval with Dynamic Batch

src/deepsparse/server/server.py, tests/server/test_endpoints.py
This is in support of monitoring for config file changes and adding/remove endpoints from a server that was already started.
You can post to `/endpoints` to add an endpoint, and delete to `/endpoints` to delete an endpoint.
Tested via unit tests
=> Adding endpoints to dynamically add/remove pipelines

src/deepsparse/loggers/prometheus_logger.py, tests/server/test_prometheus.py
https://prometheus.io/docs/practices/naming/
hyphens are not allowed in metric names.
test plan: added regression test, tested multi model example in readme
=> Fixing bug with prometheus metric name

tests/deepsparse/pipelines/test_pipeline.py
I'm unsure if this addresses the issue on github workflows
=> Attempting to improve flakiness of async timing tests

tests/server/test_hot_reloading.py
The previous way of spinning up a separate server process had a couple problems:
1. it was flaky
2. it was slow
3. it didn't really work well on github actions
This PR removes that test and replaces it with:
1. Tests that the hot_config_reload flag of start_server properly calls start_config_watcher
2. Tests that the cli commands pass the proper flag to start_server
All of this is done with mocking and click CLIRunner, so its really fast
=> Reworking hot reload config tests

src/deepsparse/image_classification/validation_script.py
Needed for EfficientNetV2-L. Tested w/ previous models and EfficientNets.
=> Added rgb kwargs to image classification dataset kwargs

src/deepsparse/server/config.py
=> [Cherry pick] Setting loggers default to None (#678)

setup.py, src/deepsparse/version.py, utils/artifacts.py
* [ent] add is_enterprise option to build version
* move is_release build to 'generated version'
=> [cherry-pick][deepsparse-ent] add is_enterprise option to build version (#686)

src/deepsparse/server/README.md, src/deepsparse/server/cli.py
Those are a couple of pathways that I think we should be more explicitly explaining to the user, especially in the context of setting up the monitoring feature.
The new pathways in the doc were tested manually.
=> Update server README.md with some additional information.

src/deepsparse/server/cli.py
=> [Cherry pick] Adding backwards compatibility for server cli (#709)

examples/benchmark/resnet50_benchmark.py
the current stub is out of date, updating to a current rn50 pruned quant stub
=> examples/benchmark/resnet50_benchmark.py - update pruned quant stub

examples/benchmark/resnet50_benchmark.py, src/deepsparse/yolo/pipelines.py, src/deepsparse/yolo/schemas.py, src/deepsparse/yolo/utils/utils.py
=> [cherry-pick] yolo multi label + benchmark stub update

src/deepsparse/version.py
=> [Cherry Pick] Bump up the DeepSparse version

src/deepsparse/transformers/eval_downstream.py, src/deepsparse/transformers/metrics.py
**test_plan:**
tested against sample model
=> eval_downstream support for go_emotions dataset

src/deepsparse/loggers/prometheus_logger.py
without this check any import of loggers will fail if prometheus is not installed
=> [Data-Logging] add protection to hard prometheus import

setup.cfg, setup.py
* Moving license_files to setup.py from setup.cfg
* Moving license_files to variable
=> [Cherry pick] Moving license_files to setup.py from setup.cfg (#790)

src/deepsparse/loggers/helpers.py, src/deepsparse/loggers/prometheus_logger.py, src/deepsparse/server/build_logger.py, tests/server/test_build_logger.py, tests/server/test_loggers.py
Cherry pick for PR: https://github.com/neuralmagic/deepsparse/pull/802
=> [Cherry Pick] Prometheus Logger logging all zeros for latency metrics

setup.py
=> [cherry-pick] update yolo max torchvision dep to 0.13

src/deepsparse/image_classification/validation_script.py
=> [cherry-pick][IC.eval] engine_type arg

src/deepsparse/image_classification/validation_script.py
=> [IC.eval] engine_type arg

src/deepsparse/loggers/prometheus_logger.py
Fix for https://app.asana.com/0/1203126676641557/1203595722894331/f
=> Prometheus logger -> mkdir for saving logs

src/deepsparse/loggers/helpers.py, src/deepsparse/loggers/prometheus_logger.py
Cherry Pick for https://github.com/neuralmagic/deepsparse/pull/833
=> [Cherry Pick] Prometheus logger -> mkdir for saving logs

setup.py
Cherry pick for: https://github.com/neuralmagic/deepsparse/pull/835
=> [Cherry Pick] Pin black version

src/deepsparse/transformers/__init__.py
Name of package was changed. Other places in the repo have already been updated
=> Use scikit-learn instead of sklearn

src/deepsparse/transformers/pipelines/question_answering.py
=> [Cherry Pick] [Fix] QA Pipeline fails on SQuAD with seq_len=128

examples/data-logging-configs/image_classification.yaml, src/deepsparse/loggers/build_logger.py, src/deepsparse/loggers/metric_functions/built_ins.py, src/deepsparse/loggers/metric_functions/computer_vision/built_ins.py, tests/deepsparse/loggers/metric_functions/helpers/test_config_generation.py, tests/deepsparse/loggers/metric_functions/helpers/test_data_config_from_predefined.py, tests/server/test_helpers.py
A series of small changes to make sure that logging functionality works as intended.
=> [MLOps 1.5] Leftover fixes before wrapping up logging 1.5

src/deepsparse/cpu.py
"trying read" -> "trying to read"
=> Add the word "to" in arch.bin error message

examples/aws-lambda/lambda-deepsparse/app/requirements.txt
updating transformers dev wheel in the requirements.txt file
=> aws-lambda update

src/deepsparse/yolo/pipelines.py, src/deepsparse/yolo/utils/utils.py, tests/test_benchmark.py
This cherry pick combines:
#964
#965
#967
And applies the net of them to 1.5 release
=> [Cherry Pick] Support for dynamic input YOLO models (1.5)

src/deepsparse/server/README.md, src/deepsparse/server/cli.py
Addresses: https://app.asana.com/0/1201735099598270/1204260174145542/f
=> Update README.md -> `log_save_frequency` in Prometheus logger 

src/deepsparse/__init__.py, src/deepsparse/analytics.py, src/deepsparse/benchmark/__init__.py, src/deepsparse/engine.py, src/deepsparse/image_classification/__init__.py, src/deepsparse/open_pif_paf/__init__.py, src/deepsparse/server/__init__.py, src/deepsparse/transformers/__init__.py, src/deepsparse/yolact/__init__.py, src/deepsparse/yolo/__init__.py
Add google analytics logging for DeepSparse. Testing -- QA will handle to ensure GA events are being populated
=> Add GA for DeepSparse

src/deepsparse/__init__.py
replaced by google analytics, version check util to be removed in future release
=> remove sparsezoo package version check

.github/workflows/build-and-publish-tagged-images.yaml, docker/Dockerfile
This  PR will update our GHA and dockerfiles:
The Dockerfile also includes support to build a dev container with the following command within `docker` directory:
```bash
DOCKER_BUILDKIT=1 \
docker build  \
--target dev \
--build-arg DEPS=dev \
--build-arg BUILDKIT_INLINE_CACHE=1 \
-t deepsparse:dev .
```
The Images will be pushed to ghcr.io and will be available under pushed packages for the repo
=> Docker Finalization

src/deepsparse/cpu.py
Enable support for Darwin in deepsparse
=> Add experimental darwin support

examples/codegen/text_generation.py, src/deepsparse/transformers/helpers.py
The PR specifies in more detail how the Codegen pipeline (and similar LLM future pipelines) will load ONNX models for inference.
(Please note that this PR still assumes separate multi-token and single-token ONNX models, this will change once the support for fixed sequence inference in the engine is ready - we will then consume a single ONNX model, overwrite the inputs, create two temporary ONNX models, and then feed the resulting two models into two separate engines.
The main highlights:
- `overwrite_transformer_onnx_model_inputs`, which is responsible for preprocessing any ONNX NLP model, was not robust enough to work with GPT-like models. I have added a callback argument, that allows for passing a custom function that will handle the overriding of the inputs.
-  adding two of the custom …
=> [CodeGen] ONNX model loading to support  >2Gb models / two engines

examples/README.md
updating lambda to "serverless" on the examples readme.
=> Quick Fix: update lambda

src/deepsparse/image_classification/README.md
=> [Fix][Docs] Update README.md to contain `image_classification` dependency

src/deepsparse/yolov8/README.md
=> [Cherry-Pick] [Fix][Docs] Remove a typo from YOLOv8 docs

setup.py
PR updates old reference of python 3.7 (it's no longer supported)
=> Update missed python version

examples/aws-sagemaker/Dockerfile, examples/aws-sagemaker/README.md, examples/aws-sagemaker/config.yaml
=> Sagemaker: update deepsparse version

examples/chatgpt-cheat-sheet/README.md
=> cheat sheet bug fix

examples/README.md
Split the examples table into two sections: cloud and demos. Also added newly added examples.
=> Examples README refresh

examples/benchmark-ui/requirements.txt
=> Benchmark UI: update deepsparse version

tests/utils/engine_mocking.py, tests/utils/test_engine_mocking.py
=> update mock engine to support cached bools arg

README.md
=> Add LLM gif to README.md

src/deepsparse/transformers/pipelines/mnli_text_classification.py
This PR adds some more info on what this attribute does!
=> [update] Description of `multi_class` attribute

.github/workflows/local-install-check.yaml
local install checks need to target building sparsezoo from src when testing installing deepsparse from src as well
=> [local-install-check.yaml] install sparsezoo from src

src/deepsparse/transformers/pipelines/text_generation.py, src/deepsparse/transformers/utils/helpers.py
- Updates defaults for max_length and max_new_tokens
- Add a function to reconcile the max_tokens to generate, based on the pipeline `sequence_length`, `prompt_sequence_length`, and the inputs provided for `max_length` and `max_new_tokens`
-  The hard cap on the total number of tokens is based on the sequence length. If max_length is provided and is less
than the sequence length, it will be used to cap the total number of tokens
generated. If it is not provided, the max_new_tokens attribute will be used and also
capped by the sequence length.
- Adds additional finish_reasons for the above conditions 
- Tested locally using the different input cases
```python
model_path="/home/dsikka/.cache/sparsezoo/neuralmagic/mpt-7b-gsm8k_mpt_pretrain-b …
```
=> [TextGeneration] Update logic for determining the max tokens generated

examples/ultralytics-yolo/ultralytics-readmes/deepsparse-readme.md
=> Fix typo in deepsparse-readme.md

README.md
=> Updated Contributors Section in readme.md

src/deepsparse/v2/operators/engine_operator.py
main idea is so that a continuous batching scheduler can 1) make multiple instances of the same engine but with different batch size 2) swap out the engine used during run to run at an arbitrary batch size
=> [v2] EngineOperator updates to make continuous batching easier

src/deepsparse/server/helpers.py, tests/server/test_helpers.py
* initial commit to unblock derek
* ready for review
* add unit test
=> [Cherry Pick] Enable preparing nested OutputSchemas for serialization (#1357)

src/deepsparse/evaluation/integrations/__init__.py, src/deepsparse/evaluation/integrations/llm_evaluation_harness.py, src/deepsparse/evaluation/utils.py, tests/deepsparse/evaluation/integrations/test_llm_evaluation_harness.py, tests/deepsparse/evaluation/test_utils.py
Implements the first evaluation integration for the DeepSparse Evaluation API:
https://github.com/EleutherAI/lm-evaluation-harness
=> [Evaluator] Implementation of `lm-evaluation-harness` integration

setup.py, src/deepsparse/evaluation/evaluator.py
Create a basic CLI for the Deepsparse Evaluation API. This CLI can be further honed in the future, as outlined here: https://github.com/neuralmagic/deepsparse/pull/1386
=> [Evaluator] Implementation of `CLI`

src/deepsparse/transformers/pipelines/pipeline.py
in the refactor to prioritize deployment directory downloads, setting the `config_path` of a transformers pipeline was lost which affects eval runs. This PR adds it back as a property that tries to read from the deployment directory
example command:
```
deepsparse.transformers.eval_downstream --dataset sst2 --engine onnxruntime zoo:bert-large-sst2_wikipedia_bookcorpus-pruned90_quantized
```
=> [bugfix] set config path correctly after deployment dir download

src/deepsparse/yolov8/README.md
=> [yolov8] readme fixes

setup.py
To match up with https://github.com/neuralmagic/sparseml/pull/1838
=> Upgrade PyTorch to 2.1

src/deepsparse/image_classification/README.md, src/deepsparse/transformers/README.md
Fixing readme code examples for:
* OPT
* sentiment analysis
* IC export
=> README example code updates

src/deepsparse/yolov8/README.md
=> [yolov8] readme command update

src/deepsparse/transformers/pipelines/question_answering.py
Fix for: https://app.asana.com/0/1205724081986514/1205993362080974
(the exhaustive explanation for this fix is in the ticket)
@dbarbuzzi this fix works for me, please confirm whether it also solves your issue)
Will cherry-pick once approved.
=> [Fix] deepsparse – tokenizer stride size issue with original transformers

setup.py, src/deepsparse/evaluation/__init__.py, src/deepsparse/evaluation/cli.py, src/deepsparse/evaluation/evaluator.py, src/deepsparse/evaluation/integrations/__init__.py, src/deepsparse/evaluation/integrations/llm_evaluation_harness.py, src/deepsparse/evaluation/registry.py, src/deepsparse/evaluation/results.py, src/deepsparse/evaluation/utils.py, src/deepsparse/server/helpers.py, src/deepsparse/server/server.py, src/deepsparse/utils/data.py, tests/deepsparse/evaluation/__init__.py, tests/deepsparse/evaluation/integrations/test_llm_evaluation_harness.py, tests/deepsparse/evaluation/test_evaluator.py, tests/deepsparse/evaluation/test_registry.py, tests/deepsparse/evaluation/test_results.py, tests/deepsparse/evaluation/test_utils.py, tests/deepsparse/utils/test_data.py, tests/server/test_helpers.py
This is a feature branch for the DeepSparse Evaluation API. This PR briefly introduces the main `evaluate` function.
The following work items are the DoD of this PR:
=> [Evaluator][Feature Branch] Implementation of `evaluate` function

src/deepsparse/transformers/pipelines/text_generation/pipeline.py
- This prompt_sequence_length condition check was added in while v2 was being developed
- Also add missing text gen docstring
=> [Text Generation][Pipeline Refactor] Add in prompt condition

src/deepsparse/transformers/pipelines/text_generation/pipeline.py, src/deepsparse/transformers/utils/helpers.py
=> [Text Generation][Pipeline Refactor] Causal Mask Check 

src/deepsparse/server/openai_server.py, src/deepsparse/transformers/pipelines/text_generation/process_outputs.py, src/deepsparse/transformers/schemas/text_generation_schemas.py
- Now that streaming works in text gen v2, enable streaming in the OpenAI server
Starting the server with `--integration openai`, we can send the python api request below
```python
import openai
from openai import OpenAI
client = OpenAI(base_url="http://localhost:5543/v1", api_key="EMPTY")
models = client.models.list()
model = "hf:mgoin/TinyStories-1M-ds"
print(f"Accessing model API '{model}'")
stream = True
completion = client.chat.completions.create(
messages="The sun shined",
stream=stream,
max_tokens=10,
model=model
)
for c in completion:
print(c)
```
Output:
```bash
ChatCompletionChunk(id='cmpl-d494a29cdd274d28a73d372356154f6f', choices=[Choice(delta=ChoiceDelta(content=' the', function_call=None, role=None, tool_calls=None), finish_reason=None, index=None)], created=1702935583, …
```
=> [OpenAI][Server] Enable OpenAI text generation streaming

README.md
=> lint on readme

src/deepsparse/server/server.py
It's the little things
before:
after:
=> Add title to server docs page

src/deepsparse/server/server.py
=> [Cherrypick] Add title to server docs page (#1525)

src/deepsparse/pipeline.py, src/deepsparse/server/server.py, src/deepsparse/subgraph_execute.py, src/deepsparse/transformers/pipelines/text_generation/generate_new_token.py, tests/deepsparse/transformers/text_generation/unit/text_generation/test_token_generation.py
- Noticed while testing the server that the async generator pathway was not using the event loop for some of the operators
- Also, remove an unnecessary check for `max_tokens` which was added for a unit test. Updated the mock data for the test instead
- All existing tests pass
- Streaming works as expected locally
```yaml
num_workers: 2
num_cores: 2
endpoints:
model: "hf:mgoin/TinyStories-1M-ds"
```
Output (streaming):
```bash
b'{"created": "2024-01-19T00:09:32.176925", "prompts": "Mario jumped", "generations": [{"text": " up", "score": null, "finished": false, "finished_reason": null}], "input_tokens": null}'
b'{"created": "2024-01-19T00:09:32.179362", "prompts": "Mario jumped", "generations": [{"text": " and", "score": null, "finished": false, "finished_reason": …
```
=> [Pipeline] Fix async generator loop

src/deepsparse/transformers/pipelines/text_generation/process_inputs.py
the tokenizer call in process inputs of the text gen pipeline has been running into a race condition in the tokenizer source code when receiving multiple concurrent requests. the issue is due to a tokenizer pass changing the tokenizers state which leads to a conflict when multiple threads try to update the tokenizer.
per @SageMoore this happens consistently on certain machines but at different points in the run
given the tokenization step is relatively fast, we will first try to lock the tokenizer call, if this becomes a bottleneck, we can look into keeping multiple tokenizers and look into potentially avoiding updating the state
**error snippet**
```python
File "/home/sage/git/wand/deepsparse/src/deepsparse/pipeline.py", line 242, in run_async
await outputs
File …
```
=> [text-gen] lock tokenizer call in process inputs

src/deepsparse/logger_v2/async_submitter.py
=> [V2 Logger]  async submitter

src/deepsparse/loggers_v2/logger_manager.py
=> [V2 Logger] logger manager

setup.py, src/deepsparse/operators/operator.py, src/deepsparse/pipeline.py, src/deepsparse/schedulers/continuous_batching_scheduler.py, src/deepsparse/server/openai_server.py, src/deepsparse/server/output.py, src/deepsparse/server/protocol.py, src/deepsparse/subgraph_execute.py, src/deepsparse/transformers/pipelines/text_generation/generate_new_token.py, src/deepsparse/transformers/pipelines/text_generation/pipeline.py, src/deepsparse/transformers/pipelines/text_generation/prep_for_generation.py, src/deepsparse/transformers/pipelines/text_generation/process_inputs.py, src/deepsparse/transformers/schemas/text_generation_schemas.py, src/deepsparse/transformers/utils/helpers.py, tests/deepsparse/schedulers/utils/test_continuous_batching_executor.py, tests/deepsparse/transformers/pipelines/test_text_generation.py, tests/deepsparse/transformers/text_generation/unit/text_generation/test_token_generation.py, tests/server/test_openai.py
credits to @dsikka for verification
=> [Cherry-Picks] for 1.7 as of Fri, Jan 19th, 2024 2:17PM

tests/logger_v2/test_loggers_pipeline.py
Tests integrating v2 loggers with pipeline. 
Checks frequency filters, tag filters, log_type entrypoint and pipeline with prometheus loggers
=> [V2 Logger] Logger with pipeline tests + prometheus

src/deepsparse/middlewares/logger_middleware.py, src/deepsparse/middlewares/timer_middleware.py, src/deepsparse/utils/state.py, tests/deepsparse/middlewares/test_logger_middleware.py, tests/utils/test_basic_logger.py
Example output 
```python3
"[metric.JoinOutput.max][⏱️0.0009205341339111328] max(JoinOutput['generated_tokens]'): 13513", "
[metric.JoinOutput.max][⏱️0.0009205341339111328] max(JoinOutput['generated_logits]'): 20.59090805053711",
[metric.GenerateNewTokenOperator.max][⏱️2.6226043701171875e-05] max(GenerateNewTokenOperator[0]['finish_reason]'): max_new_tokens", 
"[metric.GenerateNewTokenOperator.max][⏱️2.6226043701171875e-05] max(GenerateNewTokenOperator[1]['token_generator]'.token_frequencies): 1.0"
```
=> [V2 Logger] logger middleware

tests/deepsparse/transformers/text_generation/integration_tests/test_llms.py
- Quick test which was missing 
- Once the new logger is integrated with the pipeline, will need to update to add a test which makes sure we actually batch given sufficient load
=> [TextGeneration] add a test to evaluate text generation with continuous batching

tests/deepsparse/schedulers/test_continuous_batching_scheduler.py, tests/deepsparse/schedulers/utils/test_continuous_batching_executor.py, tests/deepsparse/transformers/text_generation/integration_tests/test_llms.py
- To help identify the source of seg faults during jenkins runs
=> [TextGeneration] Skip continuous batching tests

src/deepsparse/__init__.py, src/deepsparse/analyze.py
=> [Cherry Pick] Add analyze callable

src/deepsparse/server/README.md, src/deepsparse/server/cli.py, src/deepsparse/transformers/README.md, src/deepsparse/yolact/README.md, src/deepsparse/yolo/README.md
=> [Cherry Pick] Remove deprecated path + update path for new UX

src/deepsparse/server/cli.py
- Small change that was missed when adding in 1.7 UX update
- For this ticket: https://app.asana.com/0/1206109050183159/1206584891098422/f
=> [server] Fix if/else condition with new UX update

src/deepsparse/server/cli.py
=> [Cherry Pick] fix if/else conditions with new ux flow (#1599)

src/deepsparse/benchmark/benchmark_pipeline.py
=> [Cherry Pick] fix json export to remove middleware 

src/deepsparse/evaluation/cli.py, src/deepsparse/evaluation/integrations/lm_evaluation_harness.py
Cherry picks from
Fixes:
- https://app.asana.com/0/1206109050183159/1206629913669302/f
- https://app.asana.com/0/1206109050183159/1206637175194074/f
=> [Cherry pick] evaluate fixes

src/deepsparse/analyze.py
=> [Cherry pick] Propagate legacy sparsezoo analyze name change

src/deepsparse/evaluation/integrations/__init__.py
=> [Cherry Pick] Upgrade lm-eval to 0.4.1

README.md
Updated logo to match website.
=> Updated Logo in README
